// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file peoplesmarkets/report/v1/report.proto (package peoplesmarkets.report.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateReportRequest, CreateReportResponse } from "./report_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service peoplesmarkets.report.v1.ReportService
 */
export const ReportService = {
  typeName: "peoplesmarkets.report.v1.ReportService",
  methods: {
    /**
     * @generated from rpc peoplesmarkets.report.v1.ReportService.CreateReport
     */
    createReport: {
      name: "CreateReport",
      I: CreateReportRequest,
      O: CreateReportResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

