// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file sited_io/types/v1/pagination.proto (package sited_io.types.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message sited_io.types.v1.PaginationRequest
 */
export class PaginationRequest extends Message<PaginationRequest> {
  /**
   * @generated from field: uint32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: uint32 size = 2;
   */
  size = 0;

  constructor(data?: PartialMessage<PaginationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.types.v1.PaginationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PaginationRequest {
    return new PaginationRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PaginationRequest {
    return new PaginationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PaginationRequest {
    return new PaginationRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: PaginationRequest | PlainMessage<PaginationRequest> | undefined,
    b: PaginationRequest | PlainMessage<PaginationRequest> | undefined,
  ): boolean {
    return proto3.util.equals(PaginationRequest, a, b);
  }
}

/**
 * @generated from message sited_io.types.v1.PaginationResponse
 */
export class PaginationResponse extends Message<PaginationResponse> {
  /**
   * @generated from field: uint32 page = 1;
   */
  page = 0;

  /**
   * @generated from field: uint32 size = 2;
   */
  size = 0;

  /**
   * @generated from field: uint32 total_elements = 3;
   */
  totalElements = 0;

  constructor(data?: PartialMessage<PaginationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.types.v1.PaginationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "size", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    {
      no: 3,
      name: "total_elements",
      kind: "scalar",
      T: 13 /* ScalarType.UINT32 */,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PaginationResponse {
    return new PaginationResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PaginationResponse {
    return new PaginationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PaginationResponse {
    return new PaginationResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: PaginationResponse | PlainMessage<PaginationResponse> | undefined,
    b: PaginationResponse | PlainMessage<PaginationResponse> | undefined,
  ): boolean {
    return proto3.util.equals(PaginationResponse, a, b);
  }
}
