// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file peoplesmarkets/commerce/v1/shipping_rate.proto (package peoplesmarkets.commerce.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteShippingRateRequest, DeleteShippingRateResponse, GetShippingRateRequest, GetShippingRateResponse, PutShippingRateRequest, PutShippingRateResponse } from "./shipping_rate_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service peoplesmarkets.commerce.v1.ShippingRateService
 */
export const ShippingRateService = {
  typeName: "peoplesmarkets.commerce.v1.ShippingRateService",
  methods: {
    /**
     * @generated from rpc peoplesmarkets.commerce.v1.ShippingRateService.PutShippingRate
     */
    putShippingRate: {
      name: "PutShippingRate",
      I: PutShippingRateRequest,
      O: PutShippingRateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc peoplesmarkets.commerce.v1.ShippingRateService.GetShippingRate
     */
    getShippingRate: {
      name: "GetShippingRate",
      I: GetShippingRateRequest,
      O: GetShippingRateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc peoplesmarkets.commerce.v1.ShippingRateService.DeleteShippingRate
     */
    deleteShippingRate: {
      name: "DeleteShippingRate",
      I: DeleteShippingRateRequest,
      O: DeleteShippingRateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

