// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file sited_io/types/currency/v1/currency.proto (package sited_io.types.currency.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum sited_io.types.currency.v1.CurrencyCode
 */
export enum CurrencyCode {
  /**
   * @generated from enum value: CURRENCY_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CURRENCY_CODE_AED = 1;
   */
  AED = 1,

  /**
   * @generated from enum value: CURRENCY_CODE_ALL = 2;
   */
  ALL = 2,

  /**
   * @generated from enum value: CURRENCY_CODE_AMD = 3;
   */
  AMD = 3,

  /**
   * @generated from enum value: CURRENCY_CODE_ANG = 4;
   */
  ANG = 4,

  /**
   * @generated from enum value: CURRENCY_CODE_AUD = 5;
   */
  AUD = 5,

  /**
   * @generated from enum value: CURRENCY_CODE_AWG = 6;
   */
  AWG = 6,

  /**
   * @generated from enum value: CURRENCY_CODE_AZN = 7;
   */
  AZN = 7,

  /**
   * @generated from enum value: CURRENCY_CODE_BAM = 8;
   */
  BAM = 8,

  /**
   * @generated from enum value: CURRENCY_CODE_BBD = 9;
   */
  BBD = 9,

  /**
   * @generated from enum value: CURRENCY_CODE_BDT = 10;
   */
  BDT = 10,

  /**
   * @generated from enum value: CURRENCY_CODE_BGN = 11;
   */
  BGN = 11,

  /**
   * @generated from enum value: CURRENCY_CODE_BIF = 12;
   */
  BIF = 12,

  /**
   * @generated from enum value: CURRENCY_CODE_BMD = 13;
   */
  BMD = 13,

  /**
   * @generated from enum value: CURRENCY_CODE_BND = 14;
   */
  BND = 14,

  /**
   * @generated from enum value: CURRENCY_CODE_BSD = 15;
   */
  BSD = 15,

  /**
   * @generated from enum value: CURRENCY_CODE_BWP = 16;
   */
  BWP = 16,

  /**
   * @generated from enum value: CURRENCY_CODE_BYN = 17;
   */
  BYN = 17,

  /**
   * @generated from enum value: CURRENCY_CODE_BZD = 18;
   */
  BZD = 18,

  /**
   * @generated from enum value: CURRENCY_CODE_CAD = 19;
   */
  CAD = 19,

  /**
   * @generated from enum value: CURRENCY_CODE_CDF = 20;
   */
  CDF = 20,

  /**
   * @generated from enum value: CURRENCY_CODE_CHF = 21;
   */
  CHF = 21,

  /**
   * @generated from enum value: CURRENCY_CODE_CNY = 22;
   */
  CNY = 22,

  /**
   * @generated from enum value: CURRENCY_CODE_CZK = 23;
   */
  CZK = 23,

  /**
   * @generated from enum value: CURRENCY_CODE_DKK = 24;
   */
  DKK = 24,

  /**
   * @generated from enum value: CURRENCY_CODE_DOP = 25;
   */
  DOP = 25,

  /**
   * @generated from enum value: CURRENCY_CODE_DZD = 26;
   */
  DZD = 26,

  /**
   * @generated from enum value: CURRENCY_CODE_EGP = 27;
   */
  EGP = 27,

  /**
   * @generated from enum value: CURRENCY_CODE_ETB = 28;
   */
  ETB = 28,

  /**
   * @generated from enum value: CURRENCY_CODE_EUR = 29;
   */
  EUR = 29,

  /**
   * @generated from enum value: CURRENCY_CODE_FJD = 30;
   */
  FJD = 30,

  /**
   * @generated from enum value: CURRENCY_CODE_GBP = 31;
   */
  GBP = 31,

  /**
   * @generated from enum value: CURRENCY_CODE_GEL = 32;
   */
  GEL = 32,

  /**
   * @generated from enum value: CURRENCY_CODE_GIP = 33;
   */
  GIP = 33,

  /**
   * @generated from enum value: CURRENCY_CODE_GMD = 34;
   */
  GMD = 34,

  /**
   * @generated from enum value: CURRENCY_CODE_GYD = 35;
   */
  GYD = 35,

  /**
   * @generated from enum value: CURRENCY_CODE_HKD = 36;
   */
  HKD = 36,

  /**
   * @generated from enum value: CURRENCY_CODE_HTG = 37;
   */
  HTG = 37,

  /**
   * @generated from enum value: CURRENCY_CODE_HUF = 38;
   */
  HUF = 38,

  /**
   * @generated from enum value: CURRENCY_CODE_IDR = 39;
   */
  IDR = 39,

  /**
   * @generated from enum value: CURRENCY_CODE_ILS = 40;
   */
  ILS = 40,

  /**
   * @generated from enum value: CURRENCY_CODE_INR = 41;
   */
  INR = 41,

  /**
   * @generated from enum value: CURRENCY_CODE_ISK = 42;
   */
  ISK = 42,

  /**
   * @generated from enum value: CURRENCY_CODE_JMD = 43;
   */
  JMD = 43,

  /**
   * @generated from enum value: CURRENCY_CODE_JPY = 44;
   */
  JPY = 44,

  /**
   * @generated from enum value: CURRENCY_CODE_KES = 45;
   */
  KES = 45,

  /**
   * @generated from enum value: CURRENCY_CODE_KGS = 46;
   */
  KGS = 46,

  /**
   * @generated from enum value: CURRENCY_CODE_KHR = 47;
   */
  KHR = 47,

  /**
   * @generated from enum value: CURRENCY_CODE_KMF = 48;
   */
  KMF = 48,

  /**
   * @generated from enum value: CURRENCY_CODE_KRW = 49;
   */
  KRW = 49,

  /**
   * @generated from enum value: CURRENCY_CODE_KYD = 50;
   */
  KYD = 50,

  /**
   * @generated from enum value: CURRENCY_CODE_KZT = 51;
   */
  KZT = 51,

  /**
   * @generated from enum value: CURRENCY_CODE_LBP = 52;
   */
  LBP = 52,

  /**
   * @generated from enum value: CURRENCY_CODE_LKR = 53;
   */
  LKR = 53,

  /**
   * @generated from enum value: CURRENCY_CODE_LRD = 54;
   */
  LRD = 54,

  /**
   * @generated from enum value: CURRENCY_CODE_LSL = 55;
   */
  LSL = 55,

  /**
   * @generated from enum value: CURRENCY_CODE_MAD = 56;
   */
  MAD = 56,

  /**
   * @generated from enum value: CURRENCY_CODE_MDL = 57;
   */
  MDL = 57,

  /**
   * @generated from enum value: CURRENCY_CODE_MGA = 58;
   */
  MGA = 58,

  /**
   * @generated from enum value: CURRENCY_CODE_MKD = 59;
   */
  MKD = 59,

  /**
   * @generated from enum value: CURRENCY_CODE_MMK = 60;
   */
  MMK = 60,

  /**
   * @generated from enum value: CURRENCY_CODE_MNT = 61;
   */
  MNT = 61,

  /**
   * @generated from enum value: CURRENCY_CODE_MOP = 62;
   */
  MOP = 62,

  /**
   * @generated from enum value: CURRENCY_CODE_MVR = 63;
   */
  MVR = 63,

  /**
   * @generated from enum value: CURRENCY_CODE_MWK = 64;
   */
  MWK = 64,

  /**
   * @generated from enum value: CURRENCY_CODE_MXN = 65;
   */
  MXN = 65,

  /**
   * @generated from enum value: CURRENCY_CODE_MYR = 66;
   */
  MYR = 66,

  /**
   * @generated from enum value: CURRENCY_CODE_MZN = 67;
   */
  MZN = 67,

  /**
   * @generated from enum value: CURRENCY_CODE_NAD = 68;
   */
  NAD = 68,

  /**
   * @generated from enum value: CURRENCY_CODE_NGN = 69;
   */
  NGN = 69,

  /**
   * @generated from enum value: CURRENCY_CODE_NOK = 70;
   */
  NOK = 70,

  /**
   * @generated from enum value: CURRENCY_CODE_NPR = 71;
   */
  NPR = 71,

  /**
   * @generated from enum value: CURRENCY_CODE_NZD = 72;
   */
  NZD = 72,

  /**
   * @generated from enum value: CURRENCY_CODE_PGK = 73;
   */
  PGK = 73,

  /**
   * @generated from enum value: CURRENCY_CODE_PHP = 74;
   */
  PHP = 74,

  /**
   * @generated from enum value: CURRENCY_CODE_PKR = 75;
   */
  PKR = 75,

  /**
   * @generated from enum value: CURRENCY_CODE_PLN = 76;
   */
  PLN = 76,

  /**
   * @generated from enum value: CURRENCY_CODE_QAR = 77;
   */
  QAR = 77,

  /**
   * @generated from enum value: CURRENCY_CODE_RON = 78;
   */
  RON = 78,

  /**
   * @generated from enum value: CURRENCY_CODE_RSD = 79;
   */
  RSD = 79,

  /**
   * @generated from enum value: CURRENCY_CODE_RUB = 80;
   */
  RUB = 80,

  /**
   * @generated from enum value: CURRENCY_CODE_RWF = 81;
   */
  RWF = 81,

  /**
   * @generated from enum value: CURRENCY_CODE_SAR = 82;
   */
  SAR = 82,

  /**
   * @generated from enum value: CURRENCY_CODE_SBD = 83;
   */
  SBD = 83,

  /**
   * @generated from enum value: CURRENCY_CODE_SCR = 84;
   */
  SCR = 84,

  /**
   * @generated from enum value: CURRENCY_CODE_SEK = 85;
   */
  SEK = 85,

  /**
   * @generated from enum value: CURRENCY_CODE_SGD = 86;
   */
  SGD = 86,

  /**
   * @generated from enum value: CURRENCY_CODE_SLE = 87;
   */
  SLE = 87,

  /**
   * @generated from enum value: CURRENCY_CODE_SOS = 88;
   */
  SOS = 88,

  /**
   * @generated from enum value: CURRENCY_CODE_SZL = 89;
   */
  SZL = 89,

  /**
   * @generated from enum value: CURRENCY_CODE_THB = 90;
   */
  THB = 90,

  /**
   * @generated from enum value: CURRENCY_CODE_TJS = 91;
   */
  TJS = 91,

  /**
   * @generated from enum value: CURRENCY_CODE_TOP = 92;
   */
  TOP = 92,

  /**
   * @generated from enum value: CURRENCY_CODE_TRY = 93;
   */
  TRY = 93,

  /**
   * @generated from enum value: CURRENCY_CODE_TTD = 94;
   */
  TTD = 94,

  /**
   * @generated from enum value: CURRENCY_CODE_TWD = 95;
   */
  TWD = 95,

  /**
   * @generated from enum value: CURRENCY_CODE_TZS = 96;
   */
  TZS = 96,

  /**
   * @generated from enum value: CURRENCY_CODE_UAH = 97;
   */
  UAH = 97,

  /**
   * @generated from enum value: CURRENCY_CODE_UGX = 98;
   */
  UGX = 98,

  /**
   * @generated from enum value: CURRENCY_CODE_USD = 99;
   */
  USD = 99,

  /**
   * @generated from enum value: CURRENCY_CODE_UZS = 100;
   */
  UZS = 100,

  /**
   * @generated from enum value: CURRENCY_CODE_VND = 101;
   */
  VND = 101,

  /**
   * @generated from enum value: CURRENCY_CODE_VUV = 102;
   */
  VUV = 102,

  /**
   * @generated from enum value: CURRENCY_CODE_WST = 103;
   */
  WST = 103,

  /**
   * @generated from enum value: CURRENCY_CODE_XAF = 104;
   */
  XAF = 104,

  /**
   * @generated from enum value: CURRENCY_CODE_XCD = 105;
   */
  XCD = 105,

  /**
   * @generated from enum value: CURRENCY_CODE_YER = 106;
   */
  YER = 106,

  /**
   * @generated from enum value: CURRENCY_CODE_ZAR = 107;
   */
  ZAR = 107,

  /**
   * @generated from enum value: CURRENCY_CODE_ZMW = 108;
   */
  ZMW = 108,
}
// Retrieve enum metadata with: proto3.getEnumType(CurrencyCode)
proto3.util.setEnumType(CurrencyCode, "sited_io.types.currency.v1.CurrencyCode", [
  { no: 0, name: "CURRENCY_CODE_UNSPECIFIED" },
  { no: 1, name: "CURRENCY_CODE_AED" },
  { no: 2, name: "CURRENCY_CODE_ALL" },
  { no: 3, name: "CURRENCY_CODE_AMD" },
  { no: 4, name: "CURRENCY_CODE_ANG" },
  { no: 5, name: "CURRENCY_CODE_AUD" },
  { no: 6, name: "CURRENCY_CODE_AWG" },
  { no: 7, name: "CURRENCY_CODE_AZN" },
  { no: 8, name: "CURRENCY_CODE_BAM" },
  { no: 9, name: "CURRENCY_CODE_BBD" },
  { no: 10, name: "CURRENCY_CODE_BDT" },
  { no: 11, name: "CURRENCY_CODE_BGN" },
  { no: 12, name: "CURRENCY_CODE_BIF" },
  { no: 13, name: "CURRENCY_CODE_BMD" },
  { no: 14, name: "CURRENCY_CODE_BND" },
  { no: 15, name: "CURRENCY_CODE_BSD" },
  { no: 16, name: "CURRENCY_CODE_BWP" },
  { no: 17, name: "CURRENCY_CODE_BYN" },
  { no: 18, name: "CURRENCY_CODE_BZD" },
  { no: 19, name: "CURRENCY_CODE_CAD" },
  { no: 20, name: "CURRENCY_CODE_CDF" },
  { no: 21, name: "CURRENCY_CODE_CHF" },
  { no: 22, name: "CURRENCY_CODE_CNY" },
  { no: 23, name: "CURRENCY_CODE_CZK" },
  { no: 24, name: "CURRENCY_CODE_DKK" },
  { no: 25, name: "CURRENCY_CODE_DOP" },
  { no: 26, name: "CURRENCY_CODE_DZD" },
  { no: 27, name: "CURRENCY_CODE_EGP" },
  { no: 28, name: "CURRENCY_CODE_ETB" },
  { no: 29, name: "CURRENCY_CODE_EUR" },
  { no: 30, name: "CURRENCY_CODE_FJD" },
  { no: 31, name: "CURRENCY_CODE_GBP" },
  { no: 32, name: "CURRENCY_CODE_GEL" },
  { no: 33, name: "CURRENCY_CODE_GIP" },
  { no: 34, name: "CURRENCY_CODE_GMD" },
  { no: 35, name: "CURRENCY_CODE_GYD" },
  { no: 36, name: "CURRENCY_CODE_HKD" },
  { no: 37, name: "CURRENCY_CODE_HTG" },
  { no: 38, name: "CURRENCY_CODE_HUF" },
  { no: 39, name: "CURRENCY_CODE_IDR" },
  { no: 40, name: "CURRENCY_CODE_ILS" },
  { no: 41, name: "CURRENCY_CODE_INR" },
  { no: 42, name: "CURRENCY_CODE_ISK" },
  { no: 43, name: "CURRENCY_CODE_JMD" },
  { no: 44, name: "CURRENCY_CODE_JPY" },
  { no: 45, name: "CURRENCY_CODE_KES" },
  { no: 46, name: "CURRENCY_CODE_KGS" },
  { no: 47, name: "CURRENCY_CODE_KHR" },
  { no: 48, name: "CURRENCY_CODE_KMF" },
  { no: 49, name: "CURRENCY_CODE_KRW" },
  { no: 50, name: "CURRENCY_CODE_KYD" },
  { no: 51, name: "CURRENCY_CODE_KZT" },
  { no: 52, name: "CURRENCY_CODE_LBP" },
  { no: 53, name: "CURRENCY_CODE_LKR" },
  { no: 54, name: "CURRENCY_CODE_LRD" },
  { no: 55, name: "CURRENCY_CODE_LSL" },
  { no: 56, name: "CURRENCY_CODE_MAD" },
  { no: 57, name: "CURRENCY_CODE_MDL" },
  { no: 58, name: "CURRENCY_CODE_MGA" },
  { no: 59, name: "CURRENCY_CODE_MKD" },
  { no: 60, name: "CURRENCY_CODE_MMK" },
  { no: 61, name: "CURRENCY_CODE_MNT" },
  { no: 62, name: "CURRENCY_CODE_MOP" },
  { no: 63, name: "CURRENCY_CODE_MVR" },
  { no: 64, name: "CURRENCY_CODE_MWK" },
  { no: 65, name: "CURRENCY_CODE_MXN" },
  { no: 66, name: "CURRENCY_CODE_MYR" },
  { no: 67, name: "CURRENCY_CODE_MZN" },
  { no: 68, name: "CURRENCY_CODE_NAD" },
  { no: 69, name: "CURRENCY_CODE_NGN" },
  { no: 70, name: "CURRENCY_CODE_NOK" },
  { no: 71, name: "CURRENCY_CODE_NPR" },
  { no: 72, name: "CURRENCY_CODE_NZD" },
  { no: 73, name: "CURRENCY_CODE_PGK" },
  { no: 74, name: "CURRENCY_CODE_PHP" },
  { no: 75, name: "CURRENCY_CODE_PKR" },
  { no: 76, name: "CURRENCY_CODE_PLN" },
  { no: 77, name: "CURRENCY_CODE_QAR" },
  { no: 78, name: "CURRENCY_CODE_RON" },
  { no: 79, name: "CURRENCY_CODE_RSD" },
  { no: 80, name: "CURRENCY_CODE_RUB" },
  { no: 81, name: "CURRENCY_CODE_RWF" },
  { no: 82, name: "CURRENCY_CODE_SAR" },
  { no: 83, name: "CURRENCY_CODE_SBD" },
  { no: 84, name: "CURRENCY_CODE_SCR" },
  { no: 85, name: "CURRENCY_CODE_SEK" },
  { no: 86, name: "CURRENCY_CODE_SGD" },
  { no: 87, name: "CURRENCY_CODE_SLE" },
  { no: 88, name: "CURRENCY_CODE_SOS" },
  { no: 89, name: "CURRENCY_CODE_SZL" },
  { no: 90, name: "CURRENCY_CODE_THB" },
  { no: 91, name: "CURRENCY_CODE_TJS" },
  { no: 92, name: "CURRENCY_CODE_TOP" },
  { no: 93, name: "CURRENCY_CODE_TRY" },
  { no: 94, name: "CURRENCY_CODE_TTD" },
  { no: 95, name: "CURRENCY_CODE_TWD" },
  { no: 96, name: "CURRENCY_CODE_TZS" },
  { no: 97, name: "CURRENCY_CODE_UAH" },
  { no: 98, name: "CURRENCY_CODE_UGX" },
  { no: 99, name: "CURRENCY_CODE_USD" },
  { no: 100, name: "CURRENCY_CODE_UZS" },
  { no: 101, name: "CURRENCY_CODE_VND" },
  { no: 102, name: "CURRENCY_CODE_VUV" },
  { no: 103, name: "CURRENCY_CODE_WST" },
  { no: 104, name: "CURRENCY_CODE_XAF" },
  { no: 105, name: "CURRENCY_CODE_XCD" },
  { no: 106, name: "CURRENCY_CODE_YER" },
  { no: 107, name: "CURRENCY_CODE_ZAR" },
  { no: 108, name: "CURRENCY_CODE_ZMW" },
]);

