// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file sited_io/commerce/v1/shipping_rate.proto (package sited_io.commerce.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Currency } from "./price_pb.js";

/**
 * @generated from enum sited_io.commerce.v1.ShippingCountry
 */
export enum ShippingCountry {
  /**
   * @generated from enum value: SHIPPING_COUNTRY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AC = 1;
   */
  AC = 1,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AD = 2;
   */
  AD = 2,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AE = 3;
   */
  AE = 3,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AF = 4;
   */
  AF = 4,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AG = 5;
   */
  AG = 5,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AI = 6;
   */
  AI = 6,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AL = 7;
   */
  AL = 7,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AM = 8;
   */
  AM = 8,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AO = 9;
   */
  AO = 9,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AQ = 10;
   */
  AQ = 10,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AR = 11;
   */
  AR = 11,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AT = 12;
   */
  AT = 12,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AU = 13;
   */
  AU = 13,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AW = 14;
   */
  AW = 14,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AX = 15;
   */
  AX = 15,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_AZ = 16;
   */
  AZ = 16,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BA = 17;
   */
  BA = 17,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BB = 18;
   */
  BB = 18,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BD = 19;
   */
  BD = 19,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BE = 20;
   */
  BE = 20,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BF = 21;
   */
  BF = 21,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BG = 22;
   */
  BG = 22,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BH = 23;
   */
  BH = 23,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BI = 24;
   */
  BI = 24,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BJ = 25;
   */
  BJ = 25,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BL = 26;
   */
  BL = 26,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BM = 27;
   */
  BM = 27,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BN = 28;
   */
  BN = 28,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BO = 29;
   */
  BO = 29,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BQ = 30;
   */
  BQ = 30,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BR = 31;
   */
  BR = 31,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BS = 32;
   */
  BS = 32,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BT = 33;
   */
  BT = 33,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BV = 34;
   */
  BV = 34,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BW = 35;
   */
  BW = 35,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BY = 36;
   */
  BY = 36,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_BZ = 37;
   */
  BZ = 37,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CA = 38;
   */
  CA = 38,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CD = 39;
   */
  CD = 39,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CF = 40;
   */
  CF = 40,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CG = 41;
   */
  CG = 41,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CH = 42;
   */
  CH = 42,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CI = 43;
   */
  CI = 43,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CK = 44;
   */
  CK = 44,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CL = 45;
   */
  CL = 45,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CM = 46;
   */
  CM = 46,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CN = 47;
   */
  CN = 47,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CO = 48;
   */
  CO = 48,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CR = 49;
   */
  CR = 49,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CV = 50;
   */
  CV = 50,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CW = 51;
   */
  CW = 51,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CY = 52;
   */
  CY = 52,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_CZ = 53;
   */
  CZ = 53,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_DE = 54;
   */
  DE = 54,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_DJ = 55;
   */
  DJ = 55,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_DK = 56;
   */
  DK = 56,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_DM = 57;
   */
  DM = 57,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_DO = 58;
   */
  DO = 58,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_DZ = 59;
   */
  DZ = 59,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_EC = 60;
   */
  EC = 60,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_EE = 61;
   */
  EE = 61,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_EG = 62;
   */
  EG = 62,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_EH = 63;
   */
  EH = 63,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ER = 64;
   */
  ER = 64,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ES = 65;
   */
  ES = 65,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ET = 66;
   */
  ET = 66,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_FI = 67;
   */
  FI = 67,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_FJ = 68;
   */
  FJ = 68,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_FK = 69;
   */
  FK = 69,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_FO = 70;
   */
  FO = 70,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_FR = 71;
   */
  FR = 71,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GA = 72;
   */
  GA = 72,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GB = 73;
   */
  GB = 73,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GD = 74;
   */
  GD = 74,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GE = 75;
   */
  GE = 75,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GF = 76;
   */
  GF = 76,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GG = 77;
   */
  GG = 77,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GH = 78;
   */
  GH = 78,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GI = 79;
   */
  GI = 79,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GL = 80;
   */
  GL = 80,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GM = 81;
   */
  GM = 81,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GN = 82;
   */
  GN = 82,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GP = 83;
   */
  GP = 83,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GQ = 84;
   */
  GQ = 84,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GR = 85;
   */
  GR = 85,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GS = 86;
   */
  GS = 86,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GT = 87;
   */
  GT = 87,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GU = 88;
   */
  GU = 88,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GW = 89;
   */
  GW = 89,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_GY = 90;
   */
  GY = 90,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_HK = 91;
   */
  HK = 91,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_HN = 92;
   */
  HN = 92,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_HR = 93;
   */
  HR = 93,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_HT = 94;
   */
  HT = 94,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_HU = 95;
   */
  HU = 95,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ID = 96;
   */
  ID = 96,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IE = 97;
   */
  IE = 97,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IL = 98;
   */
  IL = 98,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IM = 99;
   */
  IM = 99,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IN = 100;
   */
  IN = 100,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IO = 101;
   */
  IO = 101,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IQ = 102;
   */
  IQ = 102,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IS = 103;
   */
  IS = 103,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_IT = 104;
   */
  IT = 104,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_JE = 105;
   */
  JE = 105,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_JM = 106;
   */
  JM = 106,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_JO = 107;
   */
  JO = 107,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_JP = 108;
   */
  JP = 108,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KE = 109;
   */
  KE = 109,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KG = 110;
   */
  KG = 110,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KH = 111;
   */
  KH = 111,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KI = 112;
   */
  KI = 112,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KM = 113;
   */
  KM = 113,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KN = 114;
   */
  KN = 114,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KR = 115;
   */
  KR = 115,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KW = 116;
   */
  KW = 116,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_KY = 117;
   */
  KY = 117,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LA = 118;
   */
  LA = 118,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LB = 119;
   */
  LB = 119,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LC = 120;
   */
  LC = 120,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LI = 121;
   */
  LI = 121,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LK = 122;
   */
  LK = 122,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LR = 123;
   */
  LR = 123,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LS = 124;
   */
  LS = 124,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LT = 125;
   */
  LT = 125,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LU = 126;
   */
  LU = 126,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LV = 127;
   */
  LV = 127,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_LY = 128;
   */
  LY = 128,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MA = 129;
   */
  MA = 129,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MC = 130;
   */
  MC = 130,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MD = 131;
   */
  MD = 131,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ME = 132;
   */
  ME = 132,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MF = 133;
   */
  MF = 133,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MG = 134;
   */
  MG = 134,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MK = 135;
   */
  MK = 135,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ML = 136;
   */
  ML = 136,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MM = 137;
   */
  MM = 137,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MN = 138;
   */
  MN = 138,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MO = 139;
   */
  MO = 139,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MQ = 140;
   */
  MQ = 140,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MR = 141;
   */
  MR = 141,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MS = 142;
   */
  MS = 142,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MT = 143;
   */
  MT = 143,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MU = 144;
   */
  MU = 144,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MV = 145;
   */
  MV = 145,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MW = 146;
   */
  MW = 146,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MX = 147;
   */
  MX = 147,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MY = 148;
   */
  MY = 148,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_MZ = 149;
   */
  MZ = 149,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NA = 150;
   */
  NA = 150,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NC = 151;
   */
  NC = 151,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NE = 152;
   */
  NE = 152,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NG = 153;
   */
  NG = 153,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NI = 154;
   */
  NI = 154,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NL = 155;
   */
  NL = 155,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NO = 156;
   */
  NO = 156,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NP = 157;
   */
  NP = 157,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NR = 158;
   */
  NR = 158,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NU = 159;
   */
  NU = 159,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_NZ = 160;
   */
  NZ = 160,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_OM = 161;
   */
  OM = 161,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PA = 162;
   */
  PA = 162,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PE = 163;
   */
  PE = 163,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PF = 164;
   */
  PF = 164,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PG = 165;
   */
  PG = 165,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PH = 166;
   */
  PH = 166,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PK = 167;
   */
  PK = 167,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PL = 168;
   */
  PL = 168,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PM = 169;
   */
  PM = 169,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PN = 170;
   */
  PN = 170,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PR = 171;
   */
  PR = 171,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PS = 172;
   */
  PS = 172,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PT = 173;
   */
  PT = 173,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_PY = 174;
   */
  PY = 174,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_QA = 175;
   */
  QA = 175,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_RE = 176;
   */
  RE = 176,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_RO = 177;
   */
  RO = 177,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_RS = 178;
   */
  RS = 178,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_RU = 179;
   */
  RU = 179,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_RW = 180;
   */
  RW = 180,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SA = 181;
   */
  SA = 181,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SB = 182;
   */
  SB = 182,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SC = 183;
   */
  SC = 183,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SE = 184;
   */
  SE = 184,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SG = 185;
   */
  SG = 185,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SH = 186;
   */
  SH = 186,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SI = 187;
   */
  SI = 187,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SJ = 188;
   */
  SJ = 188,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SK = 189;
   */
  SK = 189,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SL = 190;
   */
  SL = 190,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SM = 191;
   */
  SM = 191,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SN = 192;
   */
  SN = 192,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SO = 193;
   */
  SO = 193,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SR = 194;
   */
  SR = 194,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SS = 195;
   */
  SS = 195,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ST = 196;
   */
  ST = 196,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SV = 197;
   */
  SV = 197,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SX = 198;
   */
  SX = 198,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_SZ = 199;
   */
  SZ = 199,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TA = 200;
   */
  TA = 200,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TC = 201;
   */
  TC = 201,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TD = 202;
   */
  TD = 202,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TF = 203;
   */
  TF = 203,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TG = 204;
   */
  TG = 204,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TH = 205;
   */
  TH = 205,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TJ = 206;
   */
  TJ = 206,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TK = 207;
   */
  TK = 207,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TL = 208;
   */
  TL = 208,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TM = 209;
   */
  TM = 209,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TN = 210;
   */
  TN = 210,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TO = 211;
   */
  TO = 211,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TR = 212;
   */
  TR = 212,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TT = 213;
   */
  TT = 213,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TV = 214;
   */
  TV = 214,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TW = 215;
   */
  TW = 215,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_TZ = 216;
   */
  TZ = 216,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_UA = 217;
   */
  UA = 217,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_UG = 218;
   */
  UG = 218,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_US = 219;
   */
  US = 219,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_UY = 220;
   */
  UY = 220,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_UZ = 221;
   */
  UZ = 221,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_VA = 222;
   */
  VA = 222,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_VC = 223;
   */
  VC = 223,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_VE = 224;
   */
  VE = 224,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_VG = 225;
   */
  VG = 225,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_VN = 226;
   */
  VN = 226,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_VU = 227;
   */
  VU = 227,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_WF = 228;
   */
  WF = 228,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_WS = 229;
   */
  WS = 229,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_XK = 230;
   */
  XK = 230,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_YE = 231;
   */
  YE = 231,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_YT = 232;
   */
  YT = 232,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ZA = 233;
   */
  ZA = 233,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ZM = 234;
   */
  ZM = 234,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ZW = 235;
   */
  ZW = 235,

  /**
   * @generated from enum value: SHIPPING_COUNTRY_ZZ = 236;
   */
  ZZ = 236,
}
// Retrieve enum metadata with: proto3.getEnumType(ShippingCountry)
proto3.util.setEnumType(ShippingCountry, "sited_io.commerce.v1.ShippingCountry", [
  { no: 0, name: "SHIPPING_COUNTRY_UNSPECIFIED" },
  { no: 1, name: "SHIPPING_COUNTRY_AC" },
  { no: 2, name: "SHIPPING_COUNTRY_AD" },
  { no: 3, name: "SHIPPING_COUNTRY_AE" },
  { no: 4, name: "SHIPPING_COUNTRY_AF" },
  { no: 5, name: "SHIPPING_COUNTRY_AG" },
  { no: 6, name: "SHIPPING_COUNTRY_AI" },
  { no: 7, name: "SHIPPING_COUNTRY_AL" },
  { no: 8, name: "SHIPPING_COUNTRY_AM" },
  { no: 9, name: "SHIPPING_COUNTRY_AO" },
  { no: 10, name: "SHIPPING_COUNTRY_AQ" },
  { no: 11, name: "SHIPPING_COUNTRY_AR" },
  { no: 12, name: "SHIPPING_COUNTRY_AT" },
  { no: 13, name: "SHIPPING_COUNTRY_AU" },
  { no: 14, name: "SHIPPING_COUNTRY_AW" },
  { no: 15, name: "SHIPPING_COUNTRY_AX" },
  { no: 16, name: "SHIPPING_COUNTRY_AZ" },
  { no: 17, name: "SHIPPING_COUNTRY_BA" },
  { no: 18, name: "SHIPPING_COUNTRY_BB" },
  { no: 19, name: "SHIPPING_COUNTRY_BD" },
  { no: 20, name: "SHIPPING_COUNTRY_BE" },
  { no: 21, name: "SHIPPING_COUNTRY_BF" },
  { no: 22, name: "SHIPPING_COUNTRY_BG" },
  { no: 23, name: "SHIPPING_COUNTRY_BH" },
  { no: 24, name: "SHIPPING_COUNTRY_BI" },
  { no: 25, name: "SHIPPING_COUNTRY_BJ" },
  { no: 26, name: "SHIPPING_COUNTRY_BL" },
  { no: 27, name: "SHIPPING_COUNTRY_BM" },
  { no: 28, name: "SHIPPING_COUNTRY_BN" },
  { no: 29, name: "SHIPPING_COUNTRY_BO" },
  { no: 30, name: "SHIPPING_COUNTRY_BQ" },
  { no: 31, name: "SHIPPING_COUNTRY_BR" },
  { no: 32, name: "SHIPPING_COUNTRY_BS" },
  { no: 33, name: "SHIPPING_COUNTRY_BT" },
  { no: 34, name: "SHIPPING_COUNTRY_BV" },
  { no: 35, name: "SHIPPING_COUNTRY_BW" },
  { no: 36, name: "SHIPPING_COUNTRY_BY" },
  { no: 37, name: "SHIPPING_COUNTRY_BZ" },
  { no: 38, name: "SHIPPING_COUNTRY_CA" },
  { no: 39, name: "SHIPPING_COUNTRY_CD" },
  { no: 40, name: "SHIPPING_COUNTRY_CF" },
  { no: 41, name: "SHIPPING_COUNTRY_CG" },
  { no: 42, name: "SHIPPING_COUNTRY_CH" },
  { no: 43, name: "SHIPPING_COUNTRY_CI" },
  { no: 44, name: "SHIPPING_COUNTRY_CK" },
  { no: 45, name: "SHIPPING_COUNTRY_CL" },
  { no: 46, name: "SHIPPING_COUNTRY_CM" },
  { no: 47, name: "SHIPPING_COUNTRY_CN" },
  { no: 48, name: "SHIPPING_COUNTRY_CO" },
  { no: 49, name: "SHIPPING_COUNTRY_CR" },
  { no: 50, name: "SHIPPING_COUNTRY_CV" },
  { no: 51, name: "SHIPPING_COUNTRY_CW" },
  { no: 52, name: "SHIPPING_COUNTRY_CY" },
  { no: 53, name: "SHIPPING_COUNTRY_CZ" },
  { no: 54, name: "SHIPPING_COUNTRY_DE" },
  { no: 55, name: "SHIPPING_COUNTRY_DJ" },
  { no: 56, name: "SHIPPING_COUNTRY_DK" },
  { no: 57, name: "SHIPPING_COUNTRY_DM" },
  { no: 58, name: "SHIPPING_COUNTRY_DO" },
  { no: 59, name: "SHIPPING_COUNTRY_DZ" },
  { no: 60, name: "SHIPPING_COUNTRY_EC" },
  { no: 61, name: "SHIPPING_COUNTRY_EE" },
  { no: 62, name: "SHIPPING_COUNTRY_EG" },
  { no: 63, name: "SHIPPING_COUNTRY_EH" },
  { no: 64, name: "SHIPPING_COUNTRY_ER" },
  { no: 65, name: "SHIPPING_COUNTRY_ES" },
  { no: 66, name: "SHIPPING_COUNTRY_ET" },
  { no: 67, name: "SHIPPING_COUNTRY_FI" },
  { no: 68, name: "SHIPPING_COUNTRY_FJ" },
  { no: 69, name: "SHIPPING_COUNTRY_FK" },
  { no: 70, name: "SHIPPING_COUNTRY_FO" },
  { no: 71, name: "SHIPPING_COUNTRY_FR" },
  { no: 72, name: "SHIPPING_COUNTRY_GA" },
  { no: 73, name: "SHIPPING_COUNTRY_GB" },
  { no: 74, name: "SHIPPING_COUNTRY_GD" },
  { no: 75, name: "SHIPPING_COUNTRY_GE" },
  { no: 76, name: "SHIPPING_COUNTRY_GF" },
  { no: 77, name: "SHIPPING_COUNTRY_GG" },
  { no: 78, name: "SHIPPING_COUNTRY_GH" },
  { no: 79, name: "SHIPPING_COUNTRY_GI" },
  { no: 80, name: "SHIPPING_COUNTRY_GL" },
  { no: 81, name: "SHIPPING_COUNTRY_GM" },
  { no: 82, name: "SHIPPING_COUNTRY_GN" },
  { no: 83, name: "SHIPPING_COUNTRY_GP" },
  { no: 84, name: "SHIPPING_COUNTRY_GQ" },
  { no: 85, name: "SHIPPING_COUNTRY_GR" },
  { no: 86, name: "SHIPPING_COUNTRY_GS" },
  { no: 87, name: "SHIPPING_COUNTRY_GT" },
  { no: 88, name: "SHIPPING_COUNTRY_GU" },
  { no: 89, name: "SHIPPING_COUNTRY_GW" },
  { no: 90, name: "SHIPPING_COUNTRY_GY" },
  { no: 91, name: "SHIPPING_COUNTRY_HK" },
  { no: 92, name: "SHIPPING_COUNTRY_HN" },
  { no: 93, name: "SHIPPING_COUNTRY_HR" },
  { no: 94, name: "SHIPPING_COUNTRY_HT" },
  { no: 95, name: "SHIPPING_COUNTRY_HU" },
  { no: 96, name: "SHIPPING_COUNTRY_ID" },
  { no: 97, name: "SHIPPING_COUNTRY_IE" },
  { no: 98, name: "SHIPPING_COUNTRY_IL" },
  { no: 99, name: "SHIPPING_COUNTRY_IM" },
  { no: 100, name: "SHIPPING_COUNTRY_IN" },
  { no: 101, name: "SHIPPING_COUNTRY_IO" },
  { no: 102, name: "SHIPPING_COUNTRY_IQ" },
  { no: 103, name: "SHIPPING_COUNTRY_IS" },
  { no: 104, name: "SHIPPING_COUNTRY_IT" },
  { no: 105, name: "SHIPPING_COUNTRY_JE" },
  { no: 106, name: "SHIPPING_COUNTRY_JM" },
  { no: 107, name: "SHIPPING_COUNTRY_JO" },
  { no: 108, name: "SHIPPING_COUNTRY_JP" },
  { no: 109, name: "SHIPPING_COUNTRY_KE" },
  { no: 110, name: "SHIPPING_COUNTRY_KG" },
  { no: 111, name: "SHIPPING_COUNTRY_KH" },
  { no: 112, name: "SHIPPING_COUNTRY_KI" },
  { no: 113, name: "SHIPPING_COUNTRY_KM" },
  { no: 114, name: "SHIPPING_COUNTRY_KN" },
  { no: 115, name: "SHIPPING_COUNTRY_KR" },
  { no: 116, name: "SHIPPING_COUNTRY_KW" },
  { no: 117, name: "SHIPPING_COUNTRY_KY" },
  { no: 118, name: "SHIPPING_COUNTRY_LA" },
  { no: 119, name: "SHIPPING_COUNTRY_LB" },
  { no: 120, name: "SHIPPING_COUNTRY_LC" },
  { no: 121, name: "SHIPPING_COUNTRY_LI" },
  { no: 122, name: "SHIPPING_COUNTRY_LK" },
  { no: 123, name: "SHIPPING_COUNTRY_LR" },
  { no: 124, name: "SHIPPING_COUNTRY_LS" },
  { no: 125, name: "SHIPPING_COUNTRY_LT" },
  { no: 126, name: "SHIPPING_COUNTRY_LU" },
  { no: 127, name: "SHIPPING_COUNTRY_LV" },
  { no: 128, name: "SHIPPING_COUNTRY_LY" },
  { no: 129, name: "SHIPPING_COUNTRY_MA" },
  { no: 130, name: "SHIPPING_COUNTRY_MC" },
  { no: 131, name: "SHIPPING_COUNTRY_MD" },
  { no: 132, name: "SHIPPING_COUNTRY_ME" },
  { no: 133, name: "SHIPPING_COUNTRY_MF" },
  { no: 134, name: "SHIPPING_COUNTRY_MG" },
  { no: 135, name: "SHIPPING_COUNTRY_MK" },
  { no: 136, name: "SHIPPING_COUNTRY_ML" },
  { no: 137, name: "SHIPPING_COUNTRY_MM" },
  { no: 138, name: "SHIPPING_COUNTRY_MN" },
  { no: 139, name: "SHIPPING_COUNTRY_MO" },
  { no: 140, name: "SHIPPING_COUNTRY_MQ" },
  { no: 141, name: "SHIPPING_COUNTRY_MR" },
  { no: 142, name: "SHIPPING_COUNTRY_MS" },
  { no: 143, name: "SHIPPING_COUNTRY_MT" },
  { no: 144, name: "SHIPPING_COUNTRY_MU" },
  { no: 145, name: "SHIPPING_COUNTRY_MV" },
  { no: 146, name: "SHIPPING_COUNTRY_MW" },
  { no: 147, name: "SHIPPING_COUNTRY_MX" },
  { no: 148, name: "SHIPPING_COUNTRY_MY" },
  { no: 149, name: "SHIPPING_COUNTRY_MZ" },
  { no: 150, name: "SHIPPING_COUNTRY_NA" },
  { no: 151, name: "SHIPPING_COUNTRY_NC" },
  { no: 152, name: "SHIPPING_COUNTRY_NE" },
  { no: 153, name: "SHIPPING_COUNTRY_NG" },
  { no: 154, name: "SHIPPING_COUNTRY_NI" },
  { no: 155, name: "SHIPPING_COUNTRY_NL" },
  { no: 156, name: "SHIPPING_COUNTRY_NO" },
  { no: 157, name: "SHIPPING_COUNTRY_NP" },
  { no: 158, name: "SHIPPING_COUNTRY_NR" },
  { no: 159, name: "SHIPPING_COUNTRY_NU" },
  { no: 160, name: "SHIPPING_COUNTRY_NZ" },
  { no: 161, name: "SHIPPING_COUNTRY_OM" },
  { no: 162, name: "SHIPPING_COUNTRY_PA" },
  { no: 163, name: "SHIPPING_COUNTRY_PE" },
  { no: 164, name: "SHIPPING_COUNTRY_PF" },
  { no: 165, name: "SHIPPING_COUNTRY_PG" },
  { no: 166, name: "SHIPPING_COUNTRY_PH" },
  { no: 167, name: "SHIPPING_COUNTRY_PK" },
  { no: 168, name: "SHIPPING_COUNTRY_PL" },
  { no: 169, name: "SHIPPING_COUNTRY_PM" },
  { no: 170, name: "SHIPPING_COUNTRY_PN" },
  { no: 171, name: "SHIPPING_COUNTRY_PR" },
  { no: 172, name: "SHIPPING_COUNTRY_PS" },
  { no: 173, name: "SHIPPING_COUNTRY_PT" },
  { no: 174, name: "SHIPPING_COUNTRY_PY" },
  { no: 175, name: "SHIPPING_COUNTRY_QA" },
  { no: 176, name: "SHIPPING_COUNTRY_RE" },
  { no: 177, name: "SHIPPING_COUNTRY_RO" },
  { no: 178, name: "SHIPPING_COUNTRY_RS" },
  { no: 179, name: "SHIPPING_COUNTRY_RU" },
  { no: 180, name: "SHIPPING_COUNTRY_RW" },
  { no: 181, name: "SHIPPING_COUNTRY_SA" },
  { no: 182, name: "SHIPPING_COUNTRY_SB" },
  { no: 183, name: "SHIPPING_COUNTRY_SC" },
  { no: 184, name: "SHIPPING_COUNTRY_SE" },
  { no: 185, name: "SHIPPING_COUNTRY_SG" },
  { no: 186, name: "SHIPPING_COUNTRY_SH" },
  { no: 187, name: "SHIPPING_COUNTRY_SI" },
  { no: 188, name: "SHIPPING_COUNTRY_SJ" },
  { no: 189, name: "SHIPPING_COUNTRY_SK" },
  { no: 190, name: "SHIPPING_COUNTRY_SL" },
  { no: 191, name: "SHIPPING_COUNTRY_SM" },
  { no: 192, name: "SHIPPING_COUNTRY_SN" },
  { no: 193, name: "SHIPPING_COUNTRY_SO" },
  { no: 194, name: "SHIPPING_COUNTRY_SR" },
  { no: 195, name: "SHIPPING_COUNTRY_SS" },
  { no: 196, name: "SHIPPING_COUNTRY_ST" },
  { no: 197, name: "SHIPPING_COUNTRY_SV" },
  { no: 198, name: "SHIPPING_COUNTRY_SX" },
  { no: 199, name: "SHIPPING_COUNTRY_SZ" },
  { no: 200, name: "SHIPPING_COUNTRY_TA" },
  { no: 201, name: "SHIPPING_COUNTRY_TC" },
  { no: 202, name: "SHIPPING_COUNTRY_TD" },
  { no: 203, name: "SHIPPING_COUNTRY_TF" },
  { no: 204, name: "SHIPPING_COUNTRY_TG" },
  { no: 205, name: "SHIPPING_COUNTRY_TH" },
  { no: 206, name: "SHIPPING_COUNTRY_TJ" },
  { no: 207, name: "SHIPPING_COUNTRY_TK" },
  { no: 208, name: "SHIPPING_COUNTRY_TL" },
  { no: 209, name: "SHIPPING_COUNTRY_TM" },
  { no: 210, name: "SHIPPING_COUNTRY_TN" },
  { no: 211, name: "SHIPPING_COUNTRY_TO" },
  { no: 212, name: "SHIPPING_COUNTRY_TR" },
  { no: 213, name: "SHIPPING_COUNTRY_TT" },
  { no: 214, name: "SHIPPING_COUNTRY_TV" },
  { no: 215, name: "SHIPPING_COUNTRY_TW" },
  { no: 216, name: "SHIPPING_COUNTRY_TZ" },
  { no: 217, name: "SHIPPING_COUNTRY_UA" },
  { no: 218, name: "SHIPPING_COUNTRY_UG" },
  { no: 219, name: "SHIPPING_COUNTRY_US" },
  { no: 220, name: "SHIPPING_COUNTRY_UY" },
  { no: 221, name: "SHIPPING_COUNTRY_UZ" },
  { no: 222, name: "SHIPPING_COUNTRY_VA" },
  { no: 223, name: "SHIPPING_COUNTRY_VC" },
  { no: 224, name: "SHIPPING_COUNTRY_VE" },
  { no: 225, name: "SHIPPING_COUNTRY_VG" },
  { no: 226, name: "SHIPPING_COUNTRY_VN" },
  { no: 227, name: "SHIPPING_COUNTRY_VU" },
  { no: 228, name: "SHIPPING_COUNTRY_WF" },
  { no: 229, name: "SHIPPING_COUNTRY_WS" },
  { no: 230, name: "SHIPPING_COUNTRY_XK" },
  { no: 231, name: "SHIPPING_COUNTRY_YE" },
  { no: 232, name: "SHIPPING_COUNTRY_YT" },
  { no: 233, name: "SHIPPING_COUNTRY_ZA" },
  { no: 234, name: "SHIPPING_COUNTRY_ZM" },
  { no: 235, name: "SHIPPING_COUNTRY_ZW" },
  { no: 236, name: "SHIPPING_COUNTRY_ZZ" },
]);

/**
 * @generated from message sited_io.commerce.v1.ShippingRateResponse
 */
export class ShippingRateResponse extends Message<ShippingRateResponse> {
  /**
   * @generated from field: string shipping_rate_id = 1;
   */
  shippingRateId = "";

  /**
   * @generated from field: string offer_id = 2;
   */
  offerId = "";

  /**
   * @generated from field: string user_id = 3;
   */
  userId = "";

  /**
   * @generated from field: uint32 amount = 4;
   */
  amount = 0;

  /**
   * @generated from field: sited_io.commerce.v1.Currency currency = 5;
   */
  currency = Currency.UNSPECIFIED;

  /**
   * @generated from field: bool all_countries = 6;
   */
  allCountries = false;

  /**
   * @generated from field: repeated sited_io.commerce.v1.ShippingCountry specific_countries = 7;
   */
  specificCountries: ShippingCountry[] = [];

  constructor(data?: PartialMessage<ShippingRateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.ShippingRateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shipping_rate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "offer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "amount", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "currency", kind: "enum", T: proto3.getEnumType(Currency) },
    { no: 6, name: "all_countries", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "specific_countries", kind: "enum", T: proto3.getEnumType(ShippingCountry), repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ShippingRateResponse {
    return new ShippingRateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ShippingRateResponse {
    return new ShippingRateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ShippingRateResponse {
    return new ShippingRateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ShippingRateResponse | PlainMessage<ShippingRateResponse> | undefined, b: ShippingRateResponse | PlainMessage<ShippingRateResponse> | undefined): boolean {
    return proto3.util.equals(ShippingRateResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutShippingRateRequest
 */
export class PutShippingRateRequest extends Message<PutShippingRateRequest> {
  /**
   * @generated from field: string offer_id = 1;
   */
  offerId = "";

  /**
   * @generated from field: uint32 amount = 2;
   */
  amount = 0;

  /**
   * @generated from field: sited_io.commerce.v1.Currency currency = 3;
   */
  currency = Currency.UNSPECIFIED;

  /**
   * @generated from field: bool all_countries = 4;
   */
  allCountries = false;

  /**
   * @generated from field: repeated sited_io.commerce.v1.ShippingCountry specific_countries = 5;
   */
  specificCountries: ShippingCountry[] = [];

  constructor(data?: PartialMessage<PutShippingRateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.PutShippingRateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "amount", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "currency", kind: "enum", T: proto3.getEnumType(Currency) },
    { no: 4, name: "all_countries", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "specific_countries", kind: "enum", T: proto3.getEnumType(ShippingCountry), repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PutShippingRateRequest {
    return new PutShippingRateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PutShippingRateRequest {
    return new PutShippingRateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PutShippingRateRequest {
    return new PutShippingRateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PutShippingRateRequest | PlainMessage<PutShippingRateRequest> | undefined, b: PutShippingRateRequest | PlainMessage<PutShippingRateRequest> | undefined): boolean {
    return proto3.util.equals(PutShippingRateRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutShippingRateResponse
 */
export class PutShippingRateResponse extends Message<PutShippingRateResponse> {
  constructor(data?: PartialMessage<PutShippingRateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.PutShippingRateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PutShippingRateResponse {
    return new PutShippingRateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PutShippingRateResponse {
    return new PutShippingRateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PutShippingRateResponse {
    return new PutShippingRateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PutShippingRateResponse | PlainMessage<PutShippingRateResponse> | undefined, b: PutShippingRateResponse | PlainMessage<PutShippingRateResponse> | undefined): boolean {
    return proto3.util.equals(PutShippingRateResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.GetShippingRateRequest
 */
export class GetShippingRateRequest extends Message<GetShippingRateRequest> {
  /**
   * @generated from field: optional string offer_id = 1;
   */
  offerId?: string;

  constructor(data?: PartialMessage<GetShippingRateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.GetShippingRateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offer_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetShippingRateRequest {
    return new GetShippingRateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetShippingRateRequest {
    return new GetShippingRateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetShippingRateRequest {
    return new GetShippingRateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetShippingRateRequest | PlainMessage<GetShippingRateRequest> | undefined, b: GetShippingRateRequest | PlainMessage<GetShippingRateRequest> | undefined): boolean {
    return proto3.util.equals(GetShippingRateRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.GetShippingRateResponse
 */
export class GetShippingRateResponse extends Message<GetShippingRateResponse> {
  /**
   * @generated from field: sited_io.commerce.v1.ShippingRateResponse shipping_rate = 1;
   */
  shippingRate?: ShippingRateResponse;

  constructor(data?: PartialMessage<GetShippingRateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.GetShippingRateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shipping_rate", kind: "message", T: ShippingRateResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetShippingRateResponse {
    return new GetShippingRateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetShippingRateResponse {
    return new GetShippingRateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetShippingRateResponse {
    return new GetShippingRateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetShippingRateResponse | PlainMessage<GetShippingRateResponse> | undefined, b: GetShippingRateResponse | PlainMessage<GetShippingRateResponse> | undefined): boolean {
    return proto3.util.equals(GetShippingRateResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.DeleteShippingRateRequest
 */
export class DeleteShippingRateRequest extends Message<DeleteShippingRateRequest> {
  /**
   * @generated from field: string shipping_rate_id = 1;
   */
  shippingRateId = "";

  constructor(data?: PartialMessage<DeleteShippingRateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.DeleteShippingRateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shipping_rate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteShippingRateRequest {
    return new DeleteShippingRateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteShippingRateRequest {
    return new DeleteShippingRateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteShippingRateRequest {
    return new DeleteShippingRateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteShippingRateRequest | PlainMessage<DeleteShippingRateRequest> | undefined, b: DeleteShippingRateRequest | PlainMessage<DeleteShippingRateRequest> | undefined): boolean {
    return proto3.util.equals(DeleteShippingRateRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.DeleteShippingRateResponse
 */
export class DeleteShippingRateResponse extends Message<DeleteShippingRateResponse> {
  constructor(data?: PartialMessage<DeleteShippingRateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.DeleteShippingRateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteShippingRateResponse {
    return new DeleteShippingRateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteShippingRateResponse {
    return new DeleteShippingRateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteShippingRateResponse {
    return new DeleteShippingRateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteShippingRateResponse | PlainMessage<DeleteShippingRateResponse> | undefined, b: DeleteShippingRateResponse | PlainMessage<DeleteShippingRateResponse> | undefined): boolean {
    return proto3.util.equals(DeleteShippingRateResponse, a, b);
  }
}

