// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file sited_io/commerce/v1/shop_customization.proto (package sited_io.commerce.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { MediaUpload } from "../../media/v1/media_pb.js";

/**
 * @generated from enum sited_io.commerce.v1.ShopLayoutType
 */
export enum ShopLayoutType {
  /**
   * @generated from enum value: SHOP_LAYOUT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SHOP_LAYOUT_TYPE_FEAD = 1;
   */
  FEAD = 1,

  /**
   * @generated from enum value: SHOP_LAYOUT_TYPE_OFFER_LIST = 2;
   */
  OFFER_LIST = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ShopLayoutType)
proto3.util.setEnumType(ShopLayoutType, "sited_io.commerce.v1.ShopLayoutType", [
  { no: 0, name: "SHOP_LAYOUT_TYPE_UNSPECIFIED" },
  { no: 1, name: "SHOP_LAYOUT_TYPE_FEAD" },
  { no: 2, name: "SHOP_LAYOUT_TYPE_OFFER_LIST" },
]);

/**
 * @generated from message sited_io.commerce.v1.ShopCustomizationResponse
 */
export class ShopCustomizationResponse extends Message<ShopCustomizationResponse> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  /**
   * @generated from field: string user_id = 2;
   */
  userId = "";

  /**
   * @generated from field: uint64 created_at = 3;
   */
  createdAt = protoInt64.zero;

  /**
   * @generated from field: uint64 updated_at = 4;
   */
  updatedAt = protoInt64.zero;

  /**
   * @generated from field: optional string logo_image_light_url = 5;
   */
  logoImageLightUrl?: string;

  /**
   * @generated from field: optional string logo_image_dark_url = 6;
   */
  logoImageDarkUrl?: string;

  /**
   * @generated from field: optional string banner_image_light_url = 7;
   */
  bannerImageLightUrl?: string;

  /**
   * @generated from field: optional string banner_image_dark_url = 8;
   */
  bannerImageDarkUrl?: string;

  /**
   * @generated from field: optional string primary_color = 9;
   */
  primaryColor?: string;

  /**
   * @generated from field: sited_io.commerce.v1.ShopLayoutType layout_type = 10;
   */
  layoutType = ShopLayoutType.UNSPECIFIED;

  constructor(data?: PartialMessage<ShopCustomizationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.ShopCustomizationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "updated_at", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    {
      no: 5,
      name: "logo_image_light_url",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 6,
      name: "logo_image_dark_url",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 7,
      name: "banner_image_light_url",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 8,
      name: "banner_image_dark_url",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 9,
      name: "primary_color",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 10,
      name: "layout_type",
      kind: "enum",
      T: proto3.getEnumType(ShopLayoutType),
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): ShopCustomizationResponse {
    return new ShopCustomizationResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): ShopCustomizationResponse {
    return new ShopCustomizationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): ShopCustomizationResponse {
    return new ShopCustomizationResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | ShopCustomizationResponse
      | PlainMessage<ShopCustomizationResponse>
      | undefined,
    b:
      | ShopCustomizationResponse
      | PlainMessage<ShopCustomizationResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(ShopCustomizationResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutShopCustomizationRequest
 */
export class PutShopCustomizationRequest extends Message<PutShopCustomizationRequest> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  /**
   * @generated from field: optional string primary_color = 2;
   */
  primaryColor?: string;

  /**
   * @generated from field: sited_io.commerce.v1.ShopLayoutType layout_type = 3;
   */
  layoutType = ShopLayoutType.UNSPECIFIED;

  constructor(data?: PartialMessage<PutShopCustomizationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.PutShopCustomizationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    {
      no: 2,
      name: "primary_color",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 3,
      name: "layout_type",
      kind: "enum",
      T: proto3.getEnumType(ShopLayoutType),
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PutShopCustomizationRequest {
    return new PutShopCustomizationRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PutShopCustomizationRequest {
    return new PutShopCustomizationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PutShopCustomizationRequest {
    return new PutShopCustomizationRequest().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | PutShopCustomizationRequest
      | PlainMessage<PutShopCustomizationRequest>
      | undefined,
    b:
      | PutShopCustomizationRequest
      | PlainMessage<PutShopCustomizationRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(PutShopCustomizationRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutShopCustomizationResponse
 */
export class PutShopCustomizationResponse extends Message<PutShopCustomizationResponse> {
  /**
   * @generated from field: sited_io.commerce.v1.ShopCustomizationResponse shop_customization = 1;
   */
  shopCustomization?: ShopCustomizationResponse;

  constructor(data?: PartialMessage<PutShopCustomizationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.PutShopCustomizationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: "shop_customization",
      kind: "message",
      T: ShopCustomizationResponse,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PutShopCustomizationResponse {
    return new PutShopCustomizationResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PutShopCustomizationResponse {
    return new PutShopCustomizationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PutShopCustomizationResponse {
    return new PutShopCustomizationResponse().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | PutShopCustomizationResponse
      | PlainMessage<PutShopCustomizationResponse>
      | undefined,
    b:
      | PutShopCustomizationResponse
      | PlainMessage<PutShopCustomizationResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(PutShopCustomizationResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.GetShopCustomizationRequest
 */
export class GetShopCustomizationRequest extends Message<GetShopCustomizationRequest> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  constructor(data?: PartialMessage<GetShopCustomizationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.GetShopCustomizationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetShopCustomizationRequest {
    return new GetShopCustomizationRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetShopCustomizationRequest {
    return new GetShopCustomizationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetShopCustomizationRequest {
    return new GetShopCustomizationRequest().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | GetShopCustomizationRequest
      | PlainMessage<GetShopCustomizationRequest>
      | undefined,
    b:
      | GetShopCustomizationRequest
      | PlainMessage<GetShopCustomizationRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetShopCustomizationRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.GetShopCustomizationResponse
 */
export class GetShopCustomizationResponse extends Message<GetShopCustomizationResponse> {
  /**
   * @generated from field: sited_io.commerce.v1.ShopCustomizationResponse shop_customization = 1;
   */
  shopCustomization?: ShopCustomizationResponse;

  constructor(data?: PartialMessage<GetShopCustomizationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.GetShopCustomizationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: "shop_customization",
      kind: "message",
      T: ShopCustomizationResponse,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetShopCustomizationResponse {
    return new GetShopCustomizationResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetShopCustomizationResponse {
    return new GetShopCustomizationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetShopCustomizationResponse {
    return new GetShopCustomizationResponse().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | GetShopCustomizationResponse
      | PlainMessage<GetShopCustomizationResponse>
      | undefined,
    b:
      | GetShopCustomizationResponse
      | PlainMessage<GetShopCustomizationResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetShopCustomizationResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.DeleteShopCustomizationRequest
 */
export class DeleteShopCustomizationRequest extends Message<DeleteShopCustomizationRequest> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  constructor(data?: PartialMessage<DeleteShopCustomizationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.DeleteShopCustomizationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): DeleteShopCustomizationRequest {
    return new DeleteShopCustomizationRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): DeleteShopCustomizationRequest {
    return new DeleteShopCustomizationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): DeleteShopCustomizationRequest {
    return new DeleteShopCustomizationRequest().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | DeleteShopCustomizationRequest
      | PlainMessage<DeleteShopCustomizationRequest>
      | undefined,
    b:
      | DeleteShopCustomizationRequest
      | PlainMessage<DeleteShopCustomizationRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(DeleteShopCustomizationRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.DeleteShopCustomizationResponse
 */
export class DeleteShopCustomizationResponse extends Message<DeleteShopCustomizationResponse> {
  constructor(data?: PartialMessage<DeleteShopCustomizationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.DeleteShopCustomizationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): DeleteShopCustomizationResponse {
    return new DeleteShopCustomizationResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): DeleteShopCustomizationResponse {
    return new DeleteShopCustomizationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): DeleteShopCustomizationResponse {
    return new DeleteShopCustomizationResponse().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | DeleteShopCustomizationResponse
      | PlainMessage<DeleteShopCustomizationResponse>
      | undefined,
    b:
      | DeleteShopCustomizationResponse
      | PlainMessage<DeleteShopCustomizationResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(DeleteShopCustomizationResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutBannerImageToShopRequest
 */
export class PutBannerImageToShopRequest extends Message<PutBannerImageToShopRequest> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  /**
   * @generated from field: sited_io.media.v1.MediaUpload image = 2;
   */
  image?: MediaUpload;

  /**
   * @generated from field: optional sited_io.media.v1.MediaUpload image_dark = 3;
   */
  imageDark?: MediaUpload;

  constructor(data?: PartialMessage<PutBannerImageToShopRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.PutBannerImageToShopRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "image", kind: "message", T: MediaUpload },
    { no: 3, name: "image_dark", kind: "message", T: MediaUpload, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PutBannerImageToShopRequest {
    return new PutBannerImageToShopRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PutBannerImageToShopRequest {
    return new PutBannerImageToShopRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PutBannerImageToShopRequest {
    return new PutBannerImageToShopRequest().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | PutBannerImageToShopRequest
      | PlainMessage<PutBannerImageToShopRequest>
      | undefined,
    b:
      | PutBannerImageToShopRequest
      | PlainMessage<PutBannerImageToShopRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(PutBannerImageToShopRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutBannerImageToShopResponse
 */
export class PutBannerImageToShopResponse extends Message<PutBannerImageToShopResponse> {
  constructor(data?: PartialMessage<PutBannerImageToShopResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.PutBannerImageToShopResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PutBannerImageToShopResponse {
    return new PutBannerImageToShopResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PutBannerImageToShopResponse {
    return new PutBannerImageToShopResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PutBannerImageToShopResponse {
    return new PutBannerImageToShopResponse().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | PutBannerImageToShopResponse
      | PlainMessage<PutBannerImageToShopResponse>
      | undefined,
    b:
      | PutBannerImageToShopResponse
      | PlainMessage<PutBannerImageToShopResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(PutBannerImageToShopResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.RemoveBannerImageFromShopRequest
 */
export class RemoveBannerImageFromShopRequest extends Message<RemoveBannerImageFromShopRequest> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  constructor(data?: PartialMessage<RemoveBannerImageFromShopRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.RemoveBannerImageFromShopRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RemoveBannerImageFromShopRequest {
    return new RemoveBannerImageFromShopRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RemoveBannerImageFromShopRequest {
    return new RemoveBannerImageFromShopRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RemoveBannerImageFromShopRequest {
    return new RemoveBannerImageFromShopRequest().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | RemoveBannerImageFromShopRequest
      | PlainMessage<RemoveBannerImageFromShopRequest>
      | undefined,
    b:
      | RemoveBannerImageFromShopRequest
      | PlainMessage<RemoveBannerImageFromShopRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(RemoveBannerImageFromShopRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.RemoveBannerImageFromShopResponse
 */
export class RemoveBannerImageFromShopResponse extends Message<RemoveBannerImageFromShopResponse> {
  constructor(data?: PartialMessage<RemoveBannerImageFromShopResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.RemoveBannerImageFromShopResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RemoveBannerImageFromShopResponse {
    return new RemoveBannerImageFromShopResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RemoveBannerImageFromShopResponse {
    return new RemoveBannerImageFromShopResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RemoveBannerImageFromShopResponse {
    return new RemoveBannerImageFromShopResponse().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | RemoveBannerImageFromShopResponse
      | PlainMessage<RemoveBannerImageFromShopResponse>
      | undefined,
    b:
      | RemoveBannerImageFromShopResponse
      | PlainMessage<RemoveBannerImageFromShopResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(RemoveBannerImageFromShopResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutLogoImageToShopRequest
 */
export class PutLogoImageToShopRequest extends Message<PutLogoImageToShopRequest> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  /**
   * @generated from field: sited_io.media.v1.MediaUpload image = 2;
   */
  image?: MediaUpload;

  /**
   * @generated from field: optional sited_io.media.v1.MediaUpload image_dark = 3;
   */
  imageDark?: MediaUpload;

  constructor(data?: PartialMessage<PutLogoImageToShopRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.PutLogoImageToShopRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "image", kind: "message", T: MediaUpload },
    { no: 3, name: "image_dark", kind: "message", T: MediaUpload, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PutLogoImageToShopRequest {
    return new PutLogoImageToShopRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PutLogoImageToShopRequest {
    return new PutLogoImageToShopRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PutLogoImageToShopRequest {
    return new PutLogoImageToShopRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | PutLogoImageToShopRequest
      | PlainMessage<PutLogoImageToShopRequest>
      | undefined,
    b:
      | PutLogoImageToShopRequest
      | PlainMessage<PutLogoImageToShopRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(PutLogoImageToShopRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.PutLogoImageToShopResponse
 */
export class PutLogoImageToShopResponse extends Message<PutLogoImageToShopResponse> {
  constructor(data?: PartialMessage<PutLogoImageToShopResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v1.PutLogoImageToShopResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PutLogoImageToShopResponse {
    return new PutLogoImageToShopResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PutLogoImageToShopResponse {
    return new PutLogoImageToShopResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PutLogoImageToShopResponse {
    return new PutLogoImageToShopResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | PutLogoImageToShopResponse
      | PlainMessage<PutLogoImageToShopResponse>
      | undefined,
    b:
      | PutLogoImageToShopResponse
      | PlainMessage<PutLogoImageToShopResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(PutLogoImageToShopResponse, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.RemoveLogoImageFromShopRequest
 */
export class RemoveLogoImageFromShopRequest extends Message<RemoveLogoImageFromShopRequest> {
  /**
   * @generated from field: string shop_id = 1;
   */
  shopId = "";

  constructor(data?: PartialMessage<RemoveLogoImageFromShopRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.RemoveLogoImageFromShopRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "shop_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RemoveLogoImageFromShopRequest {
    return new RemoveLogoImageFromShopRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RemoveLogoImageFromShopRequest {
    return new RemoveLogoImageFromShopRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RemoveLogoImageFromShopRequest {
    return new RemoveLogoImageFromShopRequest().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | RemoveLogoImageFromShopRequest
      | PlainMessage<RemoveLogoImageFromShopRequest>
      | undefined,
    b:
      | RemoveLogoImageFromShopRequest
      | PlainMessage<RemoveLogoImageFromShopRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(RemoveLogoImageFromShopRequest, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v1.RemoveLogoImageFromShopResponse
 */
export class RemoveLogoImageFromShopResponse extends Message<RemoveLogoImageFromShopResponse> {
  constructor(data?: PartialMessage<RemoveLogoImageFromShopResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName =
    "sited_io.commerce.v1.RemoveLogoImageFromShopResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RemoveLogoImageFromShopResponse {
    return new RemoveLogoImageFromShopResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RemoveLogoImageFromShopResponse {
    return new RemoveLogoImageFromShopResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RemoveLogoImageFromShopResponse {
    return new RemoveLogoImageFromShopResponse().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | RemoveLogoImageFromShopResponse
      | PlainMessage<RemoveLogoImageFromShopResponse>
      | undefined,
    b:
      | RemoveLogoImageFromShopResponse
      | PlainMessage<RemoveLogoImageFromShopResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(RemoveLogoImageFromShopResponse, a, b);
  }
}
