// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file sited_io/types/country/v1/country.proto (package sited_io.types.country.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum sited_io.types.country.v1.CountryCode
 */
export enum CountryCode {
  /**
   * @generated from enum value: COUNTRY_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: COUNTRY_CODE_AC = 1;
   */
  AC = 1,

  /**
   * @generated from enum value: COUNTRY_CODE_AD = 2;
   */
  AD = 2,

  /**
   * @generated from enum value: COUNTRY_CODE_AE = 3;
   */
  AE = 3,

  /**
   * @generated from enum value: COUNTRY_CODE_AF = 4;
   */
  AF = 4,

  /**
   * @generated from enum value: COUNTRY_CODE_AG = 5;
   */
  AG = 5,

  /**
   * @generated from enum value: COUNTRY_CODE_AI = 6;
   */
  AI = 6,

  /**
   * @generated from enum value: COUNTRY_CODE_AL = 7;
   */
  AL = 7,

  /**
   * @generated from enum value: COUNTRY_CODE_AM = 8;
   */
  AM = 8,

  /**
   * @generated from enum value: COUNTRY_CODE_AO = 9;
   */
  AO = 9,

  /**
   * @generated from enum value: COUNTRY_CODE_AQ = 10;
   */
  AQ = 10,

  /**
   * @generated from enum value: COUNTRY_CODE_AR = 11;
   */
  AR = 11,

  /**
   * @generated from enum value: COUNTRY_CODE_AT = 12;
   */
  AT = 12,

  /**
   * @generated from enum value: COUNTRY_CODE_AU = 13;
   */
  AU = 13,

  /**
   * @generated from enum value: COUNTRY_CODE_AW = 14;
   */
  AW = 14,

  /**
   * @generated from enum value: COUNTRY_CODE_AX = 15;
   */
  AX = 15,

  /**
   * @generated from enum value: COUNTRY_CODE_AZ = 16;
   */
  AZ = 16,

  /**
   * @generated from enum value: COUNTRY_CODE_BA = 17;
   */
  BA = 17,

  /**
   * @generated from enum value: COUNTRY_CODE_BB = 18;
   */
  BB = 18,

  /**
   * @generated from enum value: COUNTRY_CODE_BD = 19;
   */
  BD = 19,

  /**
   * @generated from enum value: COUNTRY_CODE_BE = 20;
   */
  BE = 20,

  /**
   * @generated from enum value: COUNTRY_CODE_BF = 21;
   */
  BF = 21,

  /**
   * @generated from enum value: COUNTRY_CODE_BG = 22;
   */
  BG = 22,

  /**
   * @generated from enum value: COUNTRY_CODE_BH = 23;
   */
  BH = 23,

  /**
   * @generated from enum value: COUNTRY_CODE_BI = 24;
   */
  BI = 24,

  /**
   * @generated from enum value: COUNTRY_CODE_BJ = 25;
   */
  BJ = 25,

  /**
   * @generated from enum value: COUNTRY_CODE_BL = 26;
   */
  BL = 26,

  /**
   * @generated from enum value: COUNTRY_CODE_BM = 27;
   */
  BM = 27,

  /**
   * @generated from enum value: COUNTRY_CODE_BN = 28;
   */
  BN = 28,

  /**
   * @generated from enum value: COUNTRY_CODE_BO = 29;
   */
  BO = 29,

  /**
   * @generated from enum value: COUNTRY_CODE_BQ = 30;
   */
  BQ = 30,

  /**
   * @generated from enum value: COUNTRY_CODE_BR = 31;
   */
  BR = 31,

  /**
   * @generated from enum value: COUNTRY_CODE_BS = 32;
   */
  BS = 32,

  /**
   * @generated from enum value: COUNTRY_CODE_BT = 33;
   */
  BT = 33,

  /**
   * @generated from enum value: COUNTRY_CODE_BV = 34;
   */
  BV = 34,

  /**
   * @generated from enum value: COUNTRY_CODE_BW = 35;
   */
  BW = 35,

  /**
   * @generated from enum value: COUNTRY_CODE_BY = 36;
   */
  BY = 36,

  /**
   * @generated from enum value: COUNTRY_CODE_BZ = 37;
   */
  BZ = 37,

  /**
   * @generated from enum value: COUNTRY_CODE_CA = 38;
   */
  CA = 38,

  /**
   * @generated from enum value: COUNTRY_CODE_CD = 39;
   */
  CD = 39,

  /**
   * @generated from enum value: COUNTRY_CODE_CF = 40;
   */
  CF = 40,

  /**
   * @generated from enum value: COUNTRY_CODE_CG = 41;
   */
  CG = 41,

  /**
   * @generated from enum value: COUNTRY_CODE_CH = 42;
   */
  CH = 42,

  /**
   * @generated from enum value: COUNTRY_CODE_CI = 43;
   */
  CI = 43,

  /**
   * @generated from enum value: COUNTRY_CODE_CK = 44;
   */
  CK = 44,

  /**
   * @generated from enum value: COUNTRY_CODE_CL = 45;
   */
  CL = 45,

  /**
   * @generated from enum value: COUNTRY_CODE_CM = 46;
   */
  CM = 46,

  /**
   * @generated from enum value: COUNTRY_CODE_CN = 47;
   */
  CN = 47,

  /**
   * @generated from enum value: COUNTRY_CODE_CO = 48;
   */
  CO = 48,

  /**
   * @generated from enum value: COUNTRY_CODE_CR = 49;
   */
  CR = 49,

  /**
   * @generated from enum value: COUNTRY_CODE_CV = 50;
   */
  CV = 50,

  /**
   * @generated from enum value: COUNTRY_CODE_CW = 51;
   */
  CW = 51,

  /**
   * @generated from enum value: COUNTRY_CODE_CY = 52;
   */
  CY = 52,

  /**
   * @generated from enum value: COUNTRY_CODE_CZ = 53;
   */
  CZ = 53,

  /**
   * @generated from enum value: COUNTRY_CODE_DE = 54;
   */
  DE = 54,

  /**
   * @generated from enum value: COUNTRY_CODE_DJ = 55;
   */
  DJ = 55,

  /**
   * @generated from enum value: COUNTRY_CODE_DK = 56;
   */
  DK = 56,

  /**
   * @generated from enum value: COUNTRY_CODE_DM = 57;
   */
  DM = 57,

  /**
   * @generated from enum value: COUNTRY_CODE_DO = 58;
   */
  DO = 58,

  /**
   * @generated from enum value: COUNTRY_CODE_DZ = 59;
   */
  DZ = 59,

  /**
   * @generated from enum value: COUNTRY_CODE_EC = 60;
   */
  EC = 60,

  /**
   * @generated from enum value: COUNTRY_CODE_EE = 61;
   */
  EE = 61,

  /**
   * @generated from enum value: COUNTRY_CODE_EG = 62;
   */
  EG = 62,

  /**
   * @generated from enum value: COUNTRY_CODE_EH = 63;
   */
  EH = 63,

  /**
   * @generated from enum value: COUNTRY_CODE_ER = 64;
   */
  ER = 64,

  /**
   * @generated from enum value: COUNTRY_CODE_ES = 65;
   */
  ES = 65,

  /**
   * @generated from enum value: COUNTRY_CODE_ET = 66;
   */
  ET = 66,

  /**
   * @generated from enum value: COUNTRY_CODE_FI = 67;
   */
  FI = 67,

  /**
   * @generated from enum value: COUNTRY_CODE_FJ = 68;
   */
  FJ = 68,

  /**
   * @generated from enum value: COUNTRY_CODE_FK = 69;
   */
  FK = 69,

  /**
   * @generated from enum value: COUNTRY_CODE_FO = 70;
   */
  FO = 70,

  /**
   * @generated from enum value: COUNTRY_CODE_FR = 71;
   */
  FR = 71,

  /**
   * @generated from enum value: COUNTRY_CODE_GA = 72;
   */
  GA = 72,

  /**
   * @generated from enum value: COUNTRY_CODE_GB = 73;
   */
  GB = 73,

  /**
   * @generated from enum value: COUNTRY_CODE_GD = 74;
   */
  GD = 74,

  /**
   * @generated from enum value: COUNTRY_CODE_GE = 75;
   */
  GE = 75,

  /**
   * @generated from enum value: COUNTRY_CODE_GF = 76;
   */
  GF = 76,

  /**
   * @generated from enum value: COUNTRY_CODE_GG = 77;
   */
  GG = 77,

  /**
   * @generated from enum value: COUNTRY_CODE_GH = 78;
   */
  GH = 78,

  /**
   * @generated from enum value: COUNTRY_CODE_GI = 79;
   */
  GI = 79,

  /**
   * @generated from enum value: COUNTRY_CODE_GL = 80;
   */
  GL = 80,

  /**
   * @generated from enum value: COUNTRY_CODE_GM = 81;
   */
  GM = 81,

  /**
   * @generated from enum value: COUNTRY_CODE_GN = 82;
   */
  GN = 82,

  /**
   * @generated from enum value: COUNTRY_CODE_GP = 83;
   */
  GP = 83,

  /**
   * @generated from enum value: COUNTRY_CODE_GQ = 84;
   */
  GQ = 84,

  /**
   * @generated from enum value: COUNTRY_CODE_GR = 85;
   */
  GR = 85,

  /**
   * @generated from enum value: COUNTRY_CODE_GS = 86;
   */
  GS = 86,

  /**
   * @generated from enum value: COUNTRY_CODE_GT = 87;
   */
  GT = 87,

  /**
   * @generated from enum value: COUNTRY_CODE_GU = 88;
   */
  GU = 88,

  /**
   * @generated from enum value: COUNTRY_CODE_GW = 89;
   */
  GW = 89,

  /**
   * @generated from enum value: COUNTRY_CODE_GY = 90;
   */
  GY = 90,

  /**
   * @generated from enum value: COUNTRY_CODE_HK = 91;
   */
  HK = 91,

  /**
   * @generated from enum value: COUNTRY_CODE_HN = 92;
   */
  HN = 92,

  /**
   * @generated from enum value: COUNTRY_CODE_HR = 93;
   */
  HR = 93,

  /**
   * @generated from enum value: COUNTRY_CODE_HT = 94;
   */
  HT = 94,

  /**
   * @generated from enum value: COUNTRY_CODE_HU = 95;
   */
  HU = 95,

  /**
   * @generated from enum value: COUNTRY_CODE_ID = 96;
   */
  ID = 96,

  /**
   * @generated from enum value: COUNTRY_CODE_IE = 97;
   */
  IE = 97,

  /**
   * @generated from enum value: COUNTRY_CODE_IL = 98;
   */
  IL = 98,

  /**
   * @generated from enum value: COUNTRY_CODE_IM = 99;
   */
  IM = 99,

  /**
   * @generated from enum value: COUNTRY_CODE_IN = 100;
   */
  IN = 100,

  /**
   * @generated from enum value: COUNTRY_CODE_IO = 101;
   */
  IO = 101,

  /**
   * @generated from enum value: COUNTRY_CODE_IQ = 102;
   */
  IQ = 102,

  /**
   * @generated from enum value: COUNTRY_CODE_IS = 103;
   */
  IS = 103,

  /**
   * @generated from enum value: COUNTRY_CODE_IT = 104;
   */
  IT = 104,

  /**
   * @generated from enum value: COUNTRY_CODE_JE = 105;
   */
  JE = 105,

  /**
   * @generated from enum value: COUNTRY_CODE_JM = 106;
   */
  JM = 106,

  /**
   * @generated from enum value: COUNTRY_CODE_JO = 107;
   */
  JO = 107,

  /**
   * @generated from enum value: COUNTRY_CODE_JP = 108;
   */
  JP = 108,

  /**
   * @generated from enum value: COUNTRY_CODE_KE = 109;
   */
  KE = 109,

  /**
   * @generated from enum value: COUNTRY_CODE_KG = 110;
   */
  KG = 110,

  /**
   * @generated from enum value: COUNTRY_CODE_KH = 111;
   */
  KH = 111,

  /**
   * @generated from enum value: COUNTRY_CODE_KI = 112;
   */
  KI = 112,

  /**
   * @generated from enum value: COUNTRY_CODE_KM = 113;
   */
  KM = 113,

  /**
   * @generated from enum value: COUNTRY_CODE_KN = 114;
   */
  KN = 114,

  /**
   * @generated from enum value: COUNTRY_CODE_KR = 115;
   */
  KR = 115,

  /**
   * @generated from enum value: COUNTRY_CODE_KW = 116;
   */
  KW = 116,

  /**
   * @generated from enum value: COUNTRY_CODE_KY = 117;
   */
  KY = 117,

  /**
   * @generated from enum value: COUNTRY_CODE_LA = 118;
   */
  LA = 118,

  /**
   * @generated from enum value: COUNTRY_CODE_LB = 119;
   */
  LB = 119,

  /**
   * @generated from enum value: COUNTRY_CODE_LC = 120;
   */
  LC = 120,

  /**
   * @generated from enum value: COUNTRY_CODE_LI = 121;
   */
  LI = 121,

  /**
   * @generated from enum value: COUNTRY_CODE_LK = 122;
   */
  LK = 122,

  /**
   * @generated from enum value: COUNTRY_CODE_LR = 123;
   */
  LR = 123,

  /**
   * @generated from enum value: COUNTRY_CODE_LS = 124;
   */
  LS = 124,

  /**
   * @generated from enum value: COUNTRY_CODE_LT = 125;
   */
  LT = 125,

  /**
   * @generated from enum value: COUNTRY_CODE_LU = 126;
   */
  LU = 126,

  /**
   * @generated from enum value: COUNTRY_CODE_LV = 127;
   */
  LV = 127,

  /**
   * @generated from enum value: COUNTRY_CODE_LY = 128;
   */
  LY = 128,

  /**
   * @generated from enum value: COUNTRY_CODE_MA = 129;
   */
  MA = 129,

  /**
   * @generated from enum value: COUNTRY_CODE_MC = 130;
   */
  MC = 130,

  /**
   * @generated from enum value: COUNTRY_CODE_MD = 131;
   */
  MD = 131,

  /**
   * @generated from enum value: COUNTRY_CODE_ME = 132;
   */
  ME = 132,

  /**
   * @generated from enum value: COUNTRY_CODE_MF = 133;
   */
  MF = 133,

  /**
   * @generated from enum value: COUNTRY_CODE_MG = 134;
   */
  MG = 134,

  /**
   * @generated from enum value: COUNTRY_CODE_MK = 135;
   */
  MK = 135,

  /**
   * @generated from enum value: COUNTRY_CODE_ML = 136;
   */
  ML = 136,

  /**
   * @generated from enum value: COUNTRY_CODE_MM = 137;
   */
  MM = 137,

  /**
   * @generated from enum value: COUNTRY_CODE_MN = 138;
   */
  MN = 138,

  /**
   * @generated from enum value: COUNTRY_CODE_MO = 139;
   */
  MO = 139,

  /**
   * @generated from enum value: COUNTRY_CODE_MQ = 140;
   */
  MQ = 140,

  /**
   * @generated from enum value: COUNTRY_CODE_MR = 141;
   */
  MR = 141,

  /**
   * @generated from enum value: COUNTRY_CODE_MS = 142;
   */
  MS = 142,

  /**
   * @generated from enum value: COUNTRY_CODE_MT = 143;
   */
  MT = 143,

  /**
   * @generated from enum value: COUNTRY_CODE_MU = 144;
   */
  MU = 144,

  /**
   * @generated from enum value: COUNTRY_CODE_MV = 145;
   */
  MV = 145,

  /**
   * @generated from enum value: COUNTRY_CODE_MW = 146;
   */
  MW = 146,

  /**
   * @generated from enum value: COUNTRY_CODE_MX = 147;
   */
  MX = 147,

  /**
   * @generated from enum value: COUNTRY_CODE_MY = 148;
   */
  MY = 148,

  /**
   * @generated from enum value: COUNTRY_CODE_MZ = 149;
   */
  MZ = 149,

  /**
   * @generated from enum value: COUNTRY_CODE_NA = 150;
   */
  NA = 150,

  /**
   * @generated from enum value: COUNTRY_CODE_NC = 151;
   */
  NC = 151,

  /**
   * @generated from enum value: COUNTRY_CODE_NE = 152;
   */
  NE = 152,

  /**
   * @generated from enum value: COUNTRY_CODE_NG = 153;
   */
  NG = 153,

  /**
   * @generated from enum value: COUNTRY_CODE_NI = 154;
   */
  NI = 154,

  /**
   * @generated from enum value: COUNTRY_CODE_NL = 155;
   */
  NL = 155,

  /**
   * @generated from enum value: COUNTRY_CODE_NO = 156;
   */
  NO = 156,

  /**
   * @generated from enum value: COUNTRY_CODE_NP = 157;
   */
  NP = 157,

  /**
   * @generated from enum value: COUNTRY_CODE_NR = 158;
   */
  NR = 158,

  /**
   * @generated from enum value: COUNTRY_CODE_NU = 159;
   */
  NU = 159,

  /**
   * @generated from enum value: COUNTRY_CODE_NZ = 160;
   */
  NZ = 160,

  /**
   * @generated from enum value: COUNTRY_CODE_OM = 161;
   */
  OM = 161,

  /**
   * @generated from enum value: COUNTRY_CODE_PA = 162;
   */
  PA = 162,

  /**
   * @generated from enum value: COUNTRY_CODE_PE = 163;
   */
  PE = 163,

  /**
   * @generated from enum value: COUNTRY_CODE_PF = 164;
   */
  PF = 164,

  /**
   * @generated from enum value: COUNTRY_CODE_PG = 165;
   */
  PG = 165,

  /**
   * @generated from enum value: COUNTRY_CODE_PH = 166;
   */
  PH = 166,

  /**
   * @generated from enum value: COUNTRY_CODE_PK = 167;
   */
  PK = 167,

  /**
   * @generated from enum value: COUNTRY_CODE_PL = 168;
   */
  PL = 168,

  /**
   * @generated from enum value: COUNTRY_CODE_PM = 169;
   */
  PM = 169,

  /**
   * @generated from enum value: COUNTRY_CODE_PN = 170;
   */
  PN = 170,

  /**
   * @generated from enum value: COUNTRY_CODE_PR = 171;
   */
  PR = 171,

  /**
   * @generated from enum value: COUNTRY_CODE_PS = 172;
   */
  PS = 172,

  /**
   * @generated from enum value: COUNTRY_CODE_PT = 173;
   */
  PT = 173,

  /**
   * @generated from enum value: COUNTRY_CODE_PY = 174;
   */
  PY = 174,

  /**
   * @generated from enum value: COUNTRY_CODE_QA = 175;
   */
  QA = 175,

  /**
   * @generated from enum value: COUNTRY_CODE_RE = 176;
   */
  RE = 176,

  /**
   * @generated from enum value: COUNTRY_CODE_RO = 177;
   */
  RO = 177,

  /**
   * @generated from enum value: COUNTRY_CODE_RS = 178;
   */
  RS = 178,

  /**
   * @generated from enum value: COUNTRY_CODE_RU = 179;
   */
  RU = 179,

  /**
   * @generated from enum value: COUNTRY_CODE_RW = 180;
   */
  RW = 180,

  /**
   * @generated from enum value: COUNTRY_CODE_SA = 181;
   */
  SA = 181,

  /**
   * @generated from enum value: COUNTRY_CODE_SB = 182;
   */
  SB = 182,

  /**
   * @generated from enum value: COUNTRY_CODE_SC = 183;
   */
  SC = 183,

  /**
   * @generated from enum value: COUNTRY_CODE_SE = 184;
   */
  SE = 184,

  /**
   * @generated from enum value: COUNTRY_CODE_SG = 185;
   */
  SG = 185,

  /**
   * @generated from enum value: COUNTRY_CODE_SH = 186;
   */
  SH = 186,

  /**
   * @generated from enum value: COUNTRY_CODE_SI = 187;
   */
  SI = 187,

  /**
   * @generated from enum value: COUNTRY_CODE_SJ = 188;
   */
  SJ = 188,

  /**
   * @generated from enum value: COUNTRY_CODE_SK = 189;
   */
  SK = 189,

  /**
   * @generated from enum value: COUNTRY_CODE_SL = 190;
   */
  SL = 190,

  /**
   * @generated from enum value: COUNTRY_CODE_SM = 191;
   */
  SM = 191,

  /**
   * @generated from enum value: COUNTRY_CODE_SN = 192;
   */
  SN = 192,

  /**
   * @generated from enum value: COUNTRY_CODE_SO = 193;
   */
  SO = 193,

  /**
   * @generated from enum value: COUNTRY_CODE_SR = 194;
   */
  SR = 194,

  /**
   * @generated from enum value: COUNTRY_CODE_SS = 195;
   */
  SS = 195,

  /**
   * @generated from enum value: COUNTRY_CODE_ST = 196;
   */
  ST = 196,

  /**
   * @generated from enum value: COUNTRY_CODE_SV = 197;
   */
  SV = 197,

  /**
   * @generated from enum value: COUNTRY_CODE_SX = 198;
   */
  SX = 198,

  /**
   * @generated from enum value: COUNTRY_CODE_SZ = 199;
   */
  SZ = 199,

  /**
   * @generated from enum value: COUNTRY_CODE_TA = 200;
   */
  TA = 200,

  /**
   * @generated from enum value: COUNTRY_CODE_TC = 201;
   */
  TC = 201,

  /**
   * @generated from enum value: COUNTRY_CODE_TD = 202;
   */
  TD = 202,

  /**
   * @generated from enum value: COUNTRY_CODE_TF = 203;
   */
  TF = 203,

  /**
   * @generated from enum value: COUNTRY_CODE_TG = 204;
   */
  TG = 204,

  /**
   * @generated from enum value: COUNTRY_CODE_TH = 205;
   */
  TH = 205,

  /**
   * @generated from enum value: COUNTRY_CODE_TJ = 206;
   */
  TJ = 206,

  /**
   * @generated from enum value: COUNTRY_CODE_TK = 207;
   */
  TK = 207,

  /**
   * @generated from enum value: COUNTRY_CODE_TL = 208;
   */
  TL = 208,

  /**
   * @generated from enum value: COUNTRY_CODE_TM = 209;
   */
  TM = 209,

  /**
   * @generated from enum value: COUNTRY_CODE_TN = 210;
   */
  TN = 210,

  /**
   * @generated from enum value: COUNTRY_CODE_TO = 211;
   */
  TO = 211,

  /**
   * @generated from enum value: COUNTRY_CODE_TR = 212;
   */
  TR = 212,

  /**
   * @generated from enum value: COUNTRY_CODE_TT = 213;
   */
  TT = 213,

  /**
   * @generated from enum value: COUNTRY_CODE_TV = 214;
   */
  TV = 214,

  /**
   * @generated from enum value: COUNTRY_CODE_TW = 215;
   */
  TW = 215,

  /**
   * @generated from enum value: COUNTRY_CODE_TZ = 216;
   */
  TZ = 216,

  /**
   * @generated from enum value: COUNTRY_CODE_UA = 217;
   */
  UA = 217,

  /**
   * @generated from enum value: COUNTRY_CODE_UG = 218;
   */
  UG = 218,

  /**
   * @generated from enum value: COUNTRY_CODE_US = 219;
   */
  US = 219,

  /**
   * @generated from enum value: COUNTRY_CODE_UY = 220;
   */
  UY = 220,

  /**
   * @generated from enum value: COUNTRY_CODE_UZ = 221;
   */
  UZ = 221,

  /**
   * @generated from enum value: COUNTRY_CODE_VA = 222;
   */
  VA = 222,

  /**
   * @generated from enum value: COUNTRY_CODE_VC = 223;
   */
  VC = 223,

  /**
   * @generated from enum value: COUNTRY_CODE_VE = 224;
   */
  VE = 224,

  /**
   * @generated from enum value: COUNTRY_CODE_VG = 225;
   */
  VG = 225,

  /**
   * @generated from enum value: COUNTRY_CODE_VN = 226;
   */
  VN = 226,

  /**
   * @generated from enum value: COUNTRY_CODE_VU = 227;
   */
  VU = 227,

  /**
   * @generated from enum value: COUNTRY_CODE_WF = 228;
   */
  WF = 228,

  /**
   * @generated from enum value: COUNTRY_CODE_WS = 229;
   */
  WS = 229,

  /**
   * @generated from enum value: COUNTRY_CODE_XK = 230;
   */
  XK = 230,

  /**
   * @generated from enum value: COUNTRY_CODE_YE = 231;
   */
  YE = 231,

  /**
   * @generated from enum value: COUNTRY_CODE_YT = 232;
   */
  YT = 232,

  /**
   * @generated from enum value: COUNTRY_CODE_ZA = 233;
   */
  ZA = 233,

  /**
   * @generated from enum value: COUNTRY_CODE_ZM = 234;
   */
  ZM = 234,

  /**
   * @generated from enum value: COUNTRY_CODE_ZW = 235;
   */
  ZW = 235,

  /**
   * @generated from enum value: COUNTRY_CODE_ZZ = 236;
   */
  ZZ = 236,
}
// Retrieve enum metadata with: proto3.getEnumType(CountryCode)
proto3.util.setEnumType(CountryCode, "sited_io.types.country.v1.CountryCode", [
  { no: 0, name: "COUNTRY_CODE_UNSPECIFIED" },
  { no: 1, name: "COUNTRY_CODE_AC" },
  { no: 2, name: "COUNTRY_CODE_AD" },
  { no: 3, name: "COUNTRY_CODE_AE" },
  { no: 4, name: "COUNTRY_CODE_AF" },
  { no: 5, name: "COUNTRY_CODE_AG" },
  { no: 6, name: "COUNTRY_CODE_AI" },
  { no: 7, name: "COUNTRY_CODE_AL" },
  { no: 8, name: "COUNTRY_CODE_AM" },
  { no: 9, name: "COUNTRY_CODE_AO" },
  { no: 10, name: "COUNTRY_CODE_AQ" },
  { no: 11, name: "COUNTRY_CODE_AR" },
  { no: 12, name: "COUNTRY_CODE_AT" },
  { no: 13, name: "COUNTRY_CODE_AU" },
  { no: 14, name: "COUNTRY_CODE_AW" },
  { no: 15, name: "COUNTRY_CODE_AX" },
  { no: 16, name: "COUNTRY_CODE_AZ" },
  { no: 17, name: "COUNTRY_CODE_BA" },
  { no: 18, name: "COUNTRY_CODE_BB" },
  { no: 19, name: "COUNTRY_CODE_BD" },
  { no: 20, name: "COUNTRY_CODE_BE" },
  { no: 21, name: "COUNTRY_CODE_BF" },
  { no: 22, name: "COUNTRY_CODE_BG" },
  { no: 23, name: "COUNTRY_CODE_BH" },
  { no: 24, name: "COUNTRY_CODE_BI" },
  { no: 25, name: "COUNTRY_CODE_BJ" },
  { no: 26, name: "COUNTRY_CODE_BL" },
  { no: 27, name: "COUNTRY_CODE_BM" },
  { no: 28, name: "COUNTRY_CODE_BN" },
  { no: 29, name: "COUNTRY_CODE_BO" },
  { no: 30, name: "COUNTRY_CODE_BQ" },
  { no: 31, name: "COUNTRY_CODE_BR" },
  { no: 32, name: "COUNTRY_CODE_BS" },
  { no: 33, name: "COUNTRY_CODE_BT" },
  { no: 34, name: "COUNTRY_CODE_BV" },
  { no: 35, name: "COUNTRY_CODE_BW" },
  { no: 36, name: "COUNTRY_CODE_BY" },
  { no: 37, name: "COUNTRY_CODE_BZ" },
  { no: 38, name: "COUNTRY_CODE_CA" },
  { no: 39, name: "COUNTRY_CODE_CD" },
  { no: 40, name: "COUNTRY_CODE_CF" },
  { no: 41, name: "COUNTRY_CODE_CG" },
  { no: 42, name: "COUNTRY_CODE_CH" },
  { no: 43, name: "COUNTRY_CODE_CI" },
  { no: 44, name: "COUNTRY_CODE_CK" },
  { no: 45, name: "COUNTRY_CODE_CL" },
  { no: 46, name: "COUNTRY_CODE_CM" },
  { no: 47, name: "COUNTRY_CODE_CN" },
  { no: 48, name: "COUNTRY_CODE_CO" },
  { no: 49, name: "COUNTRY_CODE_CR" },
  { no: 50, name: "COUNTRY_CODE_CV" },
  { no: 51, name: "COUNTRY_CODE_CW" },
  { no: 52, name: "COUNTRY_CODE_CY" },
  { no: 53, name: "COUNTRY_CODE_CZ" },
  { no: 54, name: "COUNTRY_CODE_DE" },
  { no: 55, name: "COUNTRY_CODE_DJ" },
  { no: 56, name: "COUNTRY_CODE_DK" },
  { no: 57, name: "COUNTRY_CODE_DM" },
  { no: 58, name: "COUNTRY_CODE_DO" },
  { no: 59, name: "COUNTRY_CODE_DZ" },
  { no: 60, name: "COUNTRY_CODE_EC" },
  { no: 61, name: "COUNTRY_CODE_EE" },
  { no: 62, name: "COUNTRY_CODE_EG" },
  { no: 63, name: "COUNTRY_CODE_EH" },
  { no: 64, name: "COUNTRY_CODE_ER" },
  { no: 65, name: "COUNTRY_CODE_ES" },
  { no: 66, name: "COUNTRY_CODE_ET" },
  { no: 67, name: "COUNTRY_CODE_FI" },
  { no: 68, name: "COUNTRY_CODE_FJ" },
  { no: 69, name: "COUNTRY_CODE_FK" },
  { no: 70, name: "COUNTRY_CODE_FO" },
  { no: 71, name: "COUNTRY_CODE_FR" },
  { no: 72, name: "COUNTRY_CODE_GA" },
  { no: 73, name: "COUNTRY_CODE_GB" },
  { no: 74, name: "COUNTRY_CODE_GD" },
  { no: 75, name: "COUNTRY_CODE_GE" },
  { no: 76, name: "COUNTRY_CODE_GF" },
  { no: 77, name: "COUNTRY_CODE_GG" },
  { no: 78, name: "COUNTRY_CODE_GH" },
  { no: 79, name: "COUNTRY_CODE_GI" },
  { no: 80, name: "COUNTRY_CODE_GL" },
  { no: 81, name: "COUNTRY_CODE_GM" },
  { no: 82, name: "COUNTRY_CODE_GN" },
  { no: 83, name: "COUNTRY_CODE_GP" },
  { no: 84, name: "COUNTRY_CODE_GQ" },
  { no: 85, name: "COUNTRY_CODE_GR" },
  { no: 86, name: "COUNTRY_CODE_GS" },
  { no: 87, name: "COUNTRY_CODE_GT" },
  { no: 88, name: "COUNTRY_CODE_GU" },
  { no: 89, name: "COUNTRY_CODE_GW" },
  { no: 90, name: "COUNTRY_CODE_GY" },
  { no: 91, name: "COUNTRY_CODE_HK" },
  { no: 92, name: "COUNTRY_CODE_HN" },
  { no: 93, name: "COUNTRY_CODE_HR" },
  { no: 94, name: "COUNTRY_CODE_HT" },
  { no: 95, name: "COUNTRY_CODE_HU" },
  { no: 96, name: "COUNTRY_CODE_ID" },
  { no: 97, name: "COUNTRY_CODE_IE" },
  { no: 98, name: "COUNTRY_CODE_IL" },
  { no: 99, name: "COUNTRY_CODE_IM" },
  { no: 100, name: "COUNTRY_CODE_IN" },
  { no: 101, name: "COUNTRY_CODE_IO" },
  { no: 102, name: "COUNTRY_CODE_IQ" },
  { no: 103, name: "COUNTRY_CODE_IS" },
  { no: 104, name: "COUNTRY_CODE_IT" },
  { no: 105, name: "COUNTRY_CODE_JE" },
  { no: 106, name: "COUNTRY_CODE_JM" },
  { no: 107, name: "COUNTRY_CODE_JO" },
  { no: 108, name: "COUNTRY_CODE_JP" },
  { no: 109, name: "COUNTRY_CODE_KE" },
  { no: 110, name: "COUNTRY_CODE_KG" },
  { no: 111, name: "COUNTRY_CODE_KH" },
  { no: 112, name: "COUNTRY_CODE_KI" },
  { no: 113, name: "COUNTRY_CODE_KM" },
  { no: 114, name: "COUNTRY_CODE_KN" },
  { no: 115, name: "COUNTRY_CODE_KR" },
  { no: 116, name: "COUNTRY_CODE_KW" },
  { no: 117, name: "COUNTRY_CODE_KY" },
  { no: 118, name: "COUNTRY_CODE_LA" },
  { no: 119, name: "COUNTRY_CODE_LB" },
  { no: 120, name: "COUNTRY_CODE_LC" },
  { no: 121, name: "COUNTRY_CODE_LI" },
  { no: 122, name: "COUNTRY_CODE_LK" },
  { no: 123, name: "COUNTRY_CODE_LR" },
  { no: 124, name: "COUNTRY_CODE_LS" },
  { no: 125, name: "COUNTRY_CODE_LT" },
  { no: 126, name: "COUNTRY_CODE_LU" },
  { no: 127, name: "COUNTRY_CODE_LV" },
  { no: 128, name: "COUNTRY_CODE_LY" },
  { no: 129, name: "COUNTRY_CODE_MA" },
  { no: 130, name: "COUNTRY_CODE_MC" },
  { no: 131, name: "COUNTRY_CODE_MD" },
  { no: 132, name: "COUNTRY_CODE_ME" },
  { no: 133, name: "COUNTRY_CODE_MF" },
  { no: 134, name: "COUNTRY_CODE_MG" },
  { no: 135, name: "COUNTRY_CODE_MK" },
  { no: 136, name: "COUNTRY_CODE_ML" },
  { no: 137, name: "COUNTRY_CODE_MM" },
  { no: 138, name: "COUNTRY_CODE_MN" },
  { no: 139, name: "COUNTRY_CODE_MO" },
  { no: 140, name: "COUNTRY_CODE_MQ" },
  { no: 141, name: "COUNTRY_CODE_MR" },
  { no: 142, name: "COUNTRY_CODE_MS" },
  { no: 143, name: "COUNTRY_CODE_MT" },
  { no: 144, name: "COUNTRY_CODE_MU" },
  { no: 145, name: "COUNTRY_CODE_MV" },
  { no: 146, name: "COUNTRY_CODE_MW" },
  { no: 147, name: "COUNTRY_CODE_MX" },
  { no: 148, name: "COUNTRY_CODE_MY" },
  { no: 149, name: "COUNTRY_CODE_MZ" },
  { no: 150, name: "COUNTRY_CODE_NA" },
  { no: 151, name: "COUNTRY_CODE_NC" },
  { no: 152, name: "COUNTRY_CODE_NE" },
  { no: 153, name: "COUNTRY_CODE_NG" },
  { no: 154, name: "COUNTRY_CODE_NI" },
  { no: 155, name: "COUNTRY_CODE_NL" },
  { no: 156, name: "COUNTRY_CODE_NO" },
  { no: 157, name: "COUNTRY_CODE_NP" },
  { no: 158, name: "COUNTRY_CODE_NR" },
  { no: 159, name: "COUNTRY_CODE_NU" },
  { no: 160, name: "COUNTRY_CODE_NZ" },
  { no: 161, name: "COUNTRY_CODE_OM" },
  { no: 162, name: "COUNTRY_CODE_PA" },
  { no: 163, name: "COUNTRY_CODE_PE" },
  { no: 164, name: "COUNTRY_CODE_PF" },
  { no: 165, name: "COUNTRY_CODE_PG" },
  { no: 166, name: "COUNTRY_CODE_PH" },
  { no: 167, name: "COUNTRY_CODE_PK" },
  { no: 168, name: "COUNTRY_CODE_PL" },
  { no: 169, name: "COUNTRY_CODE_PM" },
  { no: 170, name: "COUNTRY_CODE_PN" },
  { no: 171, name: "COUNTRY_CODE_PR" },
  { no: 172, name: "COUNTRY_CODE_PS" },
  { no: 173, name: "COUNTRY_CODE_PT" },
  { no: 174, name: "COUNTRY_CODE_PY" },
  { no: 175, name: "COUNTRY_CODE_QA" },
  { no: 176, name: "COUNTRY_CODE_RE" },
  { no: 177, name: "COUNTRY_CODE_RO" },
  { no: 178, name: "COUNTRY_CODE_RS" },
  { no: 179, name: "COUNTRY_CODE_RU" },
  { no: 180, name: "COUNTRY_CODE_RW" },
  { no: 181, name: "COUNTRY_CODE_SA" },
  { no: 182, name: "COUNTRY_CODE_SB" },
  { no: 183, name: "COUNTRY_CODE_SC" },
  { no: 184, name: "COUNTRY_CODE_SE" },
  { no: 185, name: "COUNTRY_CODE_SG" },
  { no: 186, name: "COUNTRY_CODE_SH" },
  { no: 187, name: "COUNTRY_CODE_SI" },
  { no: 188, name: "COUNTRY_CODE_SJ" },
  { no: 189, name: "COUNTRY_CODE_SK" },
  { no: 190, name: "COUNTRY_CODE_SL" },
  { no: 191, name: "COUNTRY_CODE_SM" },
  { no: 192, name: "COUNTRY_CODE_SN" },
  { no: 193, name: "COUNTRY_CODE_SO" },
  { no: 194, name: "COUNTRY_CODE_SR" },
  { no: 195, name: "COUNTRY_CODE_SS" },
  { no: 196, name: "COUNTRY_CODE_ST" },
  { no: 197, name: "COUNTRY_CODE_SV" },
  { no: 198, name: "COUNTRY_CODE_SX" },
  { no: 199, name: "COUNTRY_CODE_SZ" },
  { no: 200, name: "COUNTRY_CODE_TA" },
  { no: 201, name: "COUNTRY_CODE_TC" },
  { no: 202, name: "COUNTRY_CODE_TD" },
  { no: 203, name: "COUNTRY_CODE_TF" },
  { no: 204, name: "COUNTRY_CODE_TG" },
  { no: 205, name: "COUNTRY_CODE_TH" },
  { no: 206, name: "COUNTRY_CODE_TJ" },
  { no: 207, name: "COUNTRY_CODE_TK" },
  { no: 208, name: "COUNTRY_CODE_TL" },
  { no: 209, name: "COUNTRY_CODE_TM" },
  { no: 210, name: "COUNTRY_CODE_TN" },
  { no: 211, name: "COUNTRY_CODE_TO" },
  { no: 212, name: "COUNTRY_CODE_TR" },
  { no: 213, name: "COUNTRY_CODE_TT" },
  { no: 214, name: "COUNTRY_CODE_TV" },
  { no: 215, name: "COUNTRY_CODE_TW" },
  { no: 216, name: "COUNTRY_CODE_TZ" },
  { no: 217, name: "COUNTRY_CODE_UA" },
  { no: 218, name: "COUNTRY_CODE_UG" },
  { no: 219, name: "COUNTRY_CODE_US" },
  { no: 220, name: "COUNTRY_CODE_UY" },
  { no: 221, name: "COUNTRY_CODE_UZ" },
  { no: 222, name: "COUNTRY_CODE_VA" },
  { no: 223, name: "COUNTRY_CODE_VC" },
  { no: 224, name: "COUNTRY_CODE_VE" },
  { no: 225, name: "COUNTRY_CODE_VG" },
  { no: 226, name: "COUNTRY_CODE_VN" },
  { no: 227, name: "COUNTRY_CODE_VU" },
  { no: 228, name: "COUNTRY_CODE_WF" },
  { no: 229, name: "COUNTRY_CODE_WS" },
  { no: 230, name: "COUNTRY_CODE_XK" },
  { no: 231, name: "COUNTRY_CODE_YE" },
  { no: 232, name: "COUNTRY_CODE_YT" },
  { no: 233, name: "COUNTRY_CODE_ZA" },
  { no: 234, name: "COUNTRY_CODE_ZM" },
  { no: 235, name: "COUNTRY_CODE_ZW" },
  { no: 236, name: "COUNTRY_CODE_ZZ" },
]);

